### ISSUE TITLE
Docs URL "customize/config" shows "This Page Crashed"

### ISSUE THREAD

**Issue by devnoot** [continuedev/continue#2279] opened 2024-09-16 19:33 UTC
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
Browser is Chrome
```

### Description

I noticed that the URL https://docs.continue.dev/customize/config results in a "This page crashed" with the error `t.enum.map is not a function`

### To reproduce

1. Go to https://docs.continue.dev/customize/config
2. Page will flash with content
3. Result is broken page

### Log output

```Shell
Failed to load resource: net::ERR_ADDRESS_INVALID
main.70d4531c.js:2 TypeError: t.enum.map is not a function
    at t.default (8570.36074587.js:2:106782)
    at Ei (main.70d4531c.js:2:289763)
    at El (main.70d4531c.js:2:346618)
    at wc (main.70d4531c.js:2:335770)
    at yc (main.70d4531c.js:2:335698)
    at bc (main.70d4531c.js:2:335561)
    at ic (main.70d4531c.js:2:332368)
    at ac (main.70d4531c.js:2:330920)
    at k (main.70d4531c.js:2:397148)
    at MessagePort.T (main.70d4531c.js:2:397680)
ps @ main.70d4531c.js:2
main.70d4531c.js:2 TypeError: t.enum.map is not a function
    at t.default (8570.36074587.js:2:106782)
    at Ei (main.70d4531c.js:2:289763)
    at El (main.70d4531c.js:2:346618)
    at wc (main.70d4531c.js:2:335770)
    at yc (main.70d4531c.js:2:335698)
    at bc (main.70d4531c.js:2:335561)
    at ic (main.70d4531c.js:2:332368)
    at ac (main.70d4531c.js:2:330920)
    at k (main.70d4531c.js:2:397148)
    at MessagePort.T (main.70d4531c.js:2:397680)
ps @ main.70d4531c.js:2
```

**Comment by brandontthompson** [comment] 2024-09-17 00:34
It looks like the issue is here https://github.com/continuedev/continue/blame/00213771fd182bed6f89ac726940740c2a7d11ce/docs/static/schemas/config.json#L2552

to get around this I changed my fork to use

`    "ModelTitle": {
      "type": "string",
      "$ref": "/models/title"
    }`

I will admit I am not entirely sure how docusaurus works and what this is supposed to be doing.

**Comment by Patrick-Erichsen** [comment] 2024-09-19 19:17
This should be fixed! Thanks for the heads up.

**Closed by Patrick-Erichsen** 2024-09-19 19:17 UTC
Labels: area:docs, kind:bug
