### ISSUE TITLE
Failed to set up Continue extension from email

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#312] opened 2023-07-27 18:18 UTC
From email...

I'm having an error during this stage in the screenshot

![image](https://github.com/continuedev/continue/assets/13314504/c94330a3-c57a-4c89-a4c5-d5f16c52c597)

Failed to set up Continue extension. Please email us and we'll get this fixed ASAP!

Version of VS Code:

Version: 1.80.1 (Universal)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:20:23.298Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0

**Comment by sestinj** [comment] 2023-07-27 18:44
I've solved a bug that may well have been the cause of this. To be sure, we've added a feature that lets you view the server logs in `~/.continue/continue.log`. For anyone experiencing this issue, please give it another try, and if there are problems, sharing log output will help us pin down the cause. The log file can be opened via cmd+shift+p, then "Continue: View Logs".

**Comment by sestinj** [comment] 2023-07-31 21:17
An update for those watching this issue:

1. I'm working [here](https://github.com/continuedev/continue/issues/320) on a solution to bundle the python code as an executable, which I expect to ameliorate any of these problems
2. I've added documentation [here](https://github.com/continuedev/continue/tree/main/extension#troubleshooting) on how to troubleshoot this issue

**Comment by sestinj** [comment] 2023-08-03 08:35
The packaging branch has been merged, which means that this error should be completely eradicated. Closing this issue, as any further problems are probably best categorized elsewhere.

**Closed by sestinj** 2023-08-03 08:35 UTC
Labels: bug
