### ISSUE TITLE
File Conversion to Binary or Wrong File Editing When Using /edit Command

### ISSUE THREAD

**Issue by LangLangBart** [continuedev/continue#583] opened 2023-10-25 14:43 UTC
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- Continue: 0.0.413
- VSCode: 1.83.1
```

### Description

- making changes to an existing file by using  `/edit` causes trouble
  - either the wrong content is being edited or the file becomes binary and the editor can't open it

#### bisect

- issue begins with `0.1.27`

| Version | Release date             |
| ------- | ------------------------ |
| 0.1.27  | 2023-10-17T22:10:16.317Z |
| 0.1.26  | 2023-10-14T17:23:01.04Z  |

- the issue seems to be introduced with commit b176a6cb7aea1e681ed891c74285b574c7a3ee0d
  - when reverting the changes made in `server/continuedev/server/ide.py` the issue is no longer reproducible

### To reproduce

> [!NOTE]
> the `~/.continue` folder was deleted to avoid influencing the outcomes with my settings

1. navigate to the `continue/build.sh` file, and select lines 19-35; in the continue extension, type `/edit replace echo with printf`
2. press <kbd>⏎ Enter</kbd>
3. notice the issues

- Case A: file is converted to binary

![Screen Recording 2023-10-25 at 16 23 56](https://github.com/continuedev/continue/assets/92653266/d448f7f0-2ccf-4c86-a0a1-eee87802a7b6)

- Case B: wrong file is used, rather than `continue/build.sh` a completely unrelated file is being edited

![Screen Recording 2023-10-25 at 16 29 11](https://github.com/continuedev/continue/assets/92653266/a055650b-3615-4be0-9a07-2fe14d50e3d2)

**Comment by sestinj** [comment] 2023-10-25 17:04
Ok this is an incredibly odd side-effect of that change, but I think I see what's happening and the solution.

We're queueing responses by request _type_ and then taking the first item in the queue when it's ready, which means that a response from a different request could be taken if a) more than 1 response is sent for a single request, b) a second request is sent when the response was actually on its way (this is happening here), or c) the ordering of responses doesn't match the ordering of requests

So the solution is to queue by unique request IDs. This is a pretty major bug, so I'll try to get it done today

**Comment by pzaback** [comment] 2023-10-31 18:53
FWIW, I'm running into this issue as well, although instead of editing the wrong file, it appears to be copying text into the file I'm editing from an entirely different branch of the Projects directory from my active workspace. I haven't so much as looked at let alone used or edited that project in years, so I have no idea why or how it's even being accessed. While waiting for an official fix, are there any potential issues I can expect to experience if I manually revert the changes identified by Bart? It looks like this section of code is substantially refactored in the Preview version so I look forward to that reaching release status.

**Comment by LangLangBart** [comment] 2023-11-01 15:33
@pzaback

- the `0.1.40` release; seems to have resolved the issue described here

```bash
  0.1.40              2023-11-01T09:30:25.023Z ✹ 5h ago
  0.1.39 Pre-Release  2023-11-01T08:48:10.397Z ✹ 6h ago
  0.1.38 Pre-Release  2023-11-01T08:07:55.493Z ✹ 7h ago
  0.1.37 Pre-Release  2023-11-01T06:50:01.08Z ✹ 8h ago
  0.1.36 Pre-Release  2023-11-01T00:52:53.023Z ✹ 14h ago
  0.1.35 Pre-Release  2023-10-31T21:05:53.023Z ✹ 18h ago
  0.1.34 Pre-Release  2023-10-31T20:38:34.103Z ✹ 18h ago
  0.0.413             2023-10-23T03:23:34.417Z ✹ 23/Oct/23
```

**Comment by sestinj** [comment] 2023-11-01 16:56
@LangLangBart closing this issue since you've confirmed that the new version solves it. Solution was ensuring message ordering with UUIDs

**Closed by sestinj** 2023-11-01 16:56 UTC
Labels: bug
