### ISSUE TITLE
Error downloading pre-built esbuild binary for darwin-arm64?

### ISSUE THREAD

**Issue by kivo360** [continuedev/continue#1289] opened 2024-05-15 23:19 UTC
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macos 14.4.1
- Continue: 0.8.24
- IDE: vscode
```

### Description

I'm trying to download the esbuild for darwin-arm64. It's telling me the binary doesn't exist.

Is there anyway around this problem? Should I download x86, even though it's likely to be incompatible with most of my build environments?

### To reproduce

1. Setup a mac environment with an arm processor (M1 - M3)
2. Go to extensions/vscode
3. Run `yarn install`
4. Execute `npm link @continuedev/core`
5. Run `yarn package`

### Log output

```Shell
[info] Using target:  darwin-arm64
[info] Packaging extension for target  darwin-arm64
[info] npm install in extensions/vscode completed
[info] npm install in gui completed
[info] Copied gui build to Intellij extension
Copied gui build to VSCode extension
[info] Copied onnxruntime-node
[info] Copied tree-sitter wasms
[info] Downloading pre-built lancedb binary
npm WARN using --force Recommended protections disabled.
[info] Downloading pre-built esbuild binary
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) Recv failure: Connection reset by peer
Error executing command 'curl -o node_modules/@esbuild/esbuild.zip https://continue-server-binaries.s3.us-west-1.amazonaws.com/darwin-arm64/esbuild.zip':  ,,  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) Recv failure: Connection reset by peer

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sestinj** [comment] 2024-05-20 22:11
@kivo360 it may be that the problem is trying to use yarn rather than npm.

I've made a decent number changes in just the last day cleaning up the download/packaging process, so I might try starting fresh on the `preview` branch and running the `install-all-dependencies` task

**Comment by sestinj** [comment] 2024-05-23 01:25
@kivo360 This should now be resolved since we've moved back to using `npm`. I'm going to close the issue, but if you continue having problems please lmk!

**Closed by sestinj** 2024-05-23 01:25 UTC
Labels: bug
