### ISSUE TITLE
Falling back to default config settings

### ISSUE THREAD

**Issue by weirui88888** [continuedev/continue#338] opened 2023-08-03 06:33 UTC
get error like this,what happened?

```javascript
Traceback (most recent call last):

  File "continuedev/src/continuedev/core/sdk.py", line 46, in create
    config = sdk._load_config_dot_py()

  File "continuedev/src/continuedev/core/sdk.py", line 174, in _load_config_dot_py
    spec.loader.exec_module(config)

  File "<frozen importlib._bootstrap_external>", line 883, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/Users/weirui05/.continue/config.py", line 10, in <module>
    from continuedev.core.main import Step

ModuleNotFoundError: No module named 'continuedev.core'
```

**Comment by sestinj** [comment] 2023-08-03 06:39
This is because of an update to Continue that changed how the config file makes imports.

To fix: open `~/.continue/config.py` and add "continuedev.src." to the front of each import. For example, change this

```python
from continuedev.core.main import Step
from continuedev.core.sdk import ContinueSDK
from continuedev.core.models import Models
from continuedev.core.config import CustomCommand, SlashCommand, ContinueConfig
from continuedev.plugins.context_providers.github import GitHubIssuesContextProvider
from continuedev.plugins.context_providers.google import GoogleContextProvider
from continuedev.libs.llm.maybe_proxy_openai import MaybeProxyOpenAI
from continuedev.plugins.policies.default import DefaultPolicy

from continuedev.plugins.steps.open_config import OpenConfigStep
from continuedev.plugins.steps.clear_history import ClearHistoryStep
from continuedev.plugins.steps.feedback import FeedbackStep
from continuedev.plugins.steps.comment_code import CommentCodeStep
from continuedev.plugins.steps.main import EditHighlightedCodeStep
```

to this:
```python
from continuedev.src.continuedev.core.main import Step
from continuedev.src.continuedev.core.sdk import ContinueSDK
from continuedev.src.continuedev.core.models import Models
from continuedev.src.continuedev.core.config import CustomCommand, SlashCommand, ContinueConfig
from continuedev.src.continuedev.plugins.context_providers.github import GitHubIssuesContextProvider
from continuedev.src.continuedev.plugins.context_providers.google import GoogleContextProvider
from continuedev.src.continuedev.libs.llm.maybe_proxy_openai import MaybeProxyOpenAI
from continuedev.src.continuedev.plugins.policies.default import DefaultPolicy

from continuedev.src.continuedev.plugins.steps.open_config import OpenConfigStep
from continuedev.src.continuedev.plugins.steps.clear_history import ClearHistoryStep
from continuedev.src.continuedev.plugins.steps.feedback import FeedbackStep
from continuedev.src.continuedev.plugins.steps.comment_code import CommentCodeStep
from continuedev.src.continuedev.plugins.steps.main import EditHighlightedCodeStep
```

**Comment by weirui88888** [comment] 2023-08-03 06:54
> I'll add some migration code that does this automatically for other users. Let me know if there are more problems.↳

The above error is no longer reported, but when I use it, it always prompts Invalid request sent to OpenAI. Please try again.😭

**Comment by weirui88888** [comment] 2023-08-03 06:56
> > I'll add some migration code that does this automatically for other users. Let me know if there are more problems.↳↳
> 
> The above error is no longer reported, but when I use it, it always prompts Invalid request sent to OpenAI. Please try again.😭↳

**Comment by sestinj** [comment] 2023-08-03 07:01
Yes, Continue uses GPT-4. Do you expect that this would be blocked? Continue can also work with local models if you take a look here: https://continue.dev/docs/customization#change-the-default-llm

**Comment by sestinj** [comment] 2023-08-03 08:51
Curious to know whether this was helpful. Are you now able to use Continue?

**Comment by Hezhexi2002** [comment] 2023-08-03 09:36
> Curious to know whether this was helpful. Are you now able to use Continue?

Hi,I meet the same poblem when I attemp to use continue in win10:
![image](https://github.com/continuedev/continue/assets/53631206/60b3bc35-7170-40b6-8e1e-1330a590aae7)
but the log is:
```
Traceback (most recent call last):

  File "continuedev\src\continuedev\core\sdk.py", line 46, in create
    config = sdk._load_config_dot_py()

  File "continuedev\src\continuedev\core\sdk.py", line 169, in _load_config_dot_py
    path = getConfigFilePath()

  File "continuedev\src\continuedev\libs\util\paths.py", line 39, in getConfigFilePath
    with open(path, 'r') as f:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\12235\\.continue\\config.py'
```
Actually, the server can't start normally after I  run the command `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser`, and reload VS Code and continue throwing error:
`A Python virtual enviroment cannot be activated because running scripts is disabled for this user. In order to use Continue, please enable signed scripts to run with this command in PowerShell: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser, reload VS Code, and then try again.`
But just as I opened Developer: Toggle Developer Tools and reloaded vscode again in order to get Console logs in the issue template, the error disappeared but I met the problem I mentioned at the beginning

**Comment by Hezhexi2002** [comment] 2023-08-03 12:04
> > Curious to know whether this was helpful. Are you now able to use Continue?
> 
> Hi,I meet the same poblem when I attemp to use continue in win10: ![image](https://user-images.githubusercontent.com/53631206/258067407-60b3bc35-7170-40b6-8e1e-1330a590aae7.png) but the log is:
> 
> ```
> Traceback (most recent call last):
> 
>   File "continuedev\src\continuedev\core\sdk.py", line 46, in create
>     config = sdk._load_config_dot_py()
> 
>   File "continuedev\src\continuedev\core\sdk.py", line 169, in _load_config_dot_py
>     path = getConfigFilePath()
> 
>   File "continuedev\src\continuedev\libs\util\paths.py", line 39, in getConfigFilePath
>     with open(path, 'r') as f:
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\12235\\.continue\\config.py'
> ```
> 
> Actually, the server can't start normally after I run the command `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser`, and reload VS Code and continue throwing error: `A Python virtual enviroment cannot be activated because running scripts is disabled for this user. In order to use Continue, please enable signed scripts to run with this command in PowerShell: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser, reload VS Code, and then try again.` But just as I opened Developer: Toggle Developer Tools and reloaded vscode again in order to get Console logs in the issue template, the error disappeared but I met the problem I mentioned at the beginning

I just copy the content of [default_config.py](https://github.com/continuedev/continue/blob/main/continuedev/src/continuedev/libs/constants/default_config.py) to the `C:\\Users\\12235\\.continue\\config.py` which I created just now and now it works!!!
![image](https://github.com/continuedev/continue/assets/53631206/b921bef6-49f2-49a9-9a88-c25023616977)

**Comment by sestinj** [comment] 2023-08-03 17:32
@Hezhexi2002 Nice work figuring this out! This was a bug with creating config.py, which I have now fixed.

@weirui88888 Let me know if there are any more problems. It looks like things might be resolved—if so, I will close the issue.

**Comment by Hezhexi2002** [comment] 2023-08-06 14:33
> @Hezhexi2002 Nice work figuring this out! This was a bug with creating config.py, which I have now fixed.
> 
> @weirui88888 Let me know if there are any more problems. It looks like things might be resolved—if so, I will close the issue.

Hello, I apologize for bothering you here, but I'm facing a similar problem during the installation on WSL2. The issue is that the server keeps on attempting to start, and here's the relevant log:
```
  ERR cannot open vscode-remote://wsl%2Bubuntu-20.04/home/hezhexi2002/.continue/continue.log. Detail: Unable to read file 'vscode-remote://wsl+ubuntu-20.04/home/hezhexi2002/.continue/continue.log' (Error: Unable to resolve nonexistent file 'vscode-remote://wsl+ubuntu-20.04/home/hezhexi2002/.continue/continue.log'): Error: cannot open vscode-remote://wsl%2Bubuntu-20.04/home/hezhexi2002/.continue/continue.log. Detail: Unable to read file 'vscode-remote://wsl+ubuntu-20.04/home/hezhexi2002/.continue/continue.log' (Error: Unable to resolve nonexistent file 'vscode-remote://wsl+ubuntu-20.04/home/hezhexi2002/.continue/continue.log')
    at e.$g0.$tryOpenDocument (vscode-file://vscode-app/d:/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2306:36550)
DevTools failed to load source map: Could not load content for https://vscode-remote+wsl-002bubuntu-002d20-002e04.vscode-resource.vscode-cdn.net/home/hezhexi2002/.vscode-server/extensions/continue.continue-0.0.263/react-app/dist/assets/index.js.map: Connection error: net::ERR_CONNECTION_CLOSED
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/2ccd690cbff1569e4a83d7c43d45101f817401dc/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout
workbench.desktop.main.js:627   ERR socket hang up: Error: socket hang up
    at connResetException (node:internal/errors:704:14)
    at TLSSocket.socketOnEnd (node:_http_client:505:23)
    at TLSSocket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by sestinj** [comment] 2023-08-06 17:28
@Hezhexi2002 This issue is being tracked [here](https://github.com/continuedev/continue/issues/348), and I'll be working on it in the next few hours. I'll keep you updated there.

Going to close this issue as it seems the original problem has been resolved.

**Closed by sestinj** 2023-08-06 17:28 UTC
