### ISSUE TITLE
Make the model selector combo box wider

### ISSUE THREAD

**Issue by wizche** [continuedev/continue#543] opened 2023-10-11 10:06 UTC
### Validations

- [x] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

Its super difficult to read the model name and details given such a small width of the model selector combo box. No matter how wide I make vscode, the size seems to be fixed.
![2023-10-11-120337](https://github.com/continuedev/continue/assets/1062939/9f53ff88-530e-477e-87cd-120939ff3eb0)

### Solution

Make it fill the width up to the help/settings button

**Comment by Allan2000-Git** [comment] 2023-10-11 10:40
I can solve this asap. Please assign me this issue

**Comment by wizche** [comment] 2023-10-11 10:47
I'm not allowed to assign people to issues... I guess maintainers have to

**Comment by Allan2000-Git** [comment] 2023-10-11 10:54
Can you ping the maintainers to assign me this issue?
Solution: make the width to 100%, it will take up the remaining space available

**Comment by wizche** [comment] 2023-10-11 11:40
Why dont you just submit the PR ?

**Comment by Allan2000-Git** [comment] 2023-10-11 12:04
i'm not able to find the code in the repo. can you paste the link here?

**Comment by sestinj** [comment] 2023-10-11 17:08
@Allan2000-Git just assigned, happy to have you help here! The relevant code is here: https://github.com/continuedev/continue/blob/47756758d03cbf09e1229dc02521730ac305efe1/extension/react-app/src/components/ModelSelect.tsx#L113

**Comment by Allan2000-Git** [comment] 2023-10-11 17:37
i have changed the max-width to 50vw, making it 100vw could cause trouble. never make 100vw

**Comment by sestinj** [comment] 2023-10-12 16:55
Nice work! closing this issue, appreciate the contribution. The change will be reflected in an official release soon

**Closed by sestinj** 2023-10-12 16:55 UTC
Labels: enhancement

**Comment by Allan2000-Git** [comment] 2023-10-12 18:32
did the changes work as intended?

looking forward to contribute more

**Comment by sestinj** [comment] 2023-10-12 22:24
@Allan2000-Git yeah it was a perfect solution actually. Excited to have your help - let me know what questions you might have : )

**Comment by Allan2000-Git** [comment] 2023-10-13 05:46
i want to contribute more with respect to ui perspective. i'm a frontend developer looking for a part time or an internship to enhance my skills.

**Comment by sestinj** [comment] 2023-10-13 18:35
@Allan2000-Git Unfortunately we aren't currently hiring for internships or part-time, but would still love for you to play a part in the contributor community as much as you'd like. There's lots to improve in the UI and we are welcoming of PRs, or I'm happy to point you toward specific ideas we have. And either way would love to have you join [our Discord](https://discord.gg/rKEw5ZKqhu)!

**Comment by Allan2000-Git** [comment] 2023-10-14 05:50
Thank you @sestinj . It would be great if you could point me towards ui related issues or improvements

**Comment by sestinj** [comment] 2023-10-14 21:16
@Allan2000-Git we're always open to small improvements like the one here, and you might come across a number of such little details as you use Continue. One slightly larger idea is that we plan to allow deletion of past sessions from history.tsx, and so would want to have a "Trash Can" icon show up upon hover of any of the <tr>s

Many more ideas depending on the size of contribution you might want to make, and we also have a page [here](https://github.com/orgs/continuedev/projects/2) with a few listed
