### ISSUE TITLE
issues with jira context provider and incomplete documentation

### ISSUE THREAD

**Issue by bodzebod** [continuedev/continue#2226] opened 2024-09-10 08:24 UTC
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11
- Continue: 0.9.197
- IDE: vscode 1.93.0
- Model: not relevant
- config.json:
  
{
      "name": "jira",
      "params": {
        "domain": "xxx.atlassian.net",
        "token": "xxxxx",
        "email": "xxx@xxx.xxx",
        "apiVersion": 3
      }
    },
```

### Description

In the documentation for jira context provider, it is mentioned to fill only "domain" and "token" in config.json. However, I've not been able to make it work on our jira cloud. I was getting an error 403 (forbidden) systematically, until I filled the properties "email" and "apiVersion", which allowed to get a list of jira issues.
On this, the documentation looks incomplete. 

But when I reference a JIRA issue in the chat, I then get another error:
'''
Error getting context items from jira: TypeError: (0,
import_adf_to_md.default) is not a function
'''
![image](https://github.com/user-attachments/assets/cea03200-07a3-4e18-93e4-3fce6f1c5765)

So, the chat cannot get the content of the jira issue.

### To reproduce

1. ensure to have a jira cloud account, then create an API token in https://id.atlassian.com/manage-profile/security/api-tokens
2. configure the jira context provider with parameters: domain, token, email, apiVersion
3. in the chat, use the jira context provider to grab an open issue assigned to you, then click on it to reference it in the chat
4. ask a question like "what's the outcome for this ticket?"
5. you should see the error tooltip appear

### Log output

```Shell
there's nothing written in core.log or prompt.log when using this context provider.
```

**Comment by bodzebod** [comment] 2024-09-10 09:27
I found that there exists some npm modules provided by Atlassian dubbed as: [@atlaskit/adf-utils](https://www.npmjs.com/package/@atlaskit/adf-utils) . I feel like the issue is related to this module (or the absence of this module).
I'm not familiar with how to deal with npm modules and continue however. 
I tried to execute "npm install @atlaskit/adf-utils" from ~/continue folder, and reload vscode, but it doesn't change it.

**Comment by Patrick-Erichsen** [comment] 2024-09-12 19:45
Hi @bodzebod , thanks for flagging this. The issue is likely related to some TypeScript config updates we made last month. 

Should be fixed with this: https://github.com/continuedev/continue/pull/2247

Please circle back if you're still having issues after the next pre-release!

**Comment by bodzebod** [comment] 2024-09-20 12:42
it works like a charm, thank you!

**Closed** 2024-09-20 12:42 UTC
Labels: area:context-providers, area:docs, kind:bug, ide:vscode
