### ISSUE TITLE
400 error starcoder2

### ISSUE THREAD

**Issue by maverik23** [continuedev/continue#2430] opened 2024-09-30 16:34 UTC
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS Sequoia 15.1
- Continue: v0.9.213
- IDE: escode
- Model: starcoder2:3b
- config.json:
  

{
  "models": [
    {
      "title": "Llama 3.1",
      "provider": "ollama",
      "model": "llama3.1:latest"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Starcoder2 3B",
    "provider": "ollama",
    "model": "starcoder2:3b"
  },
  "embeddingsProvider": {
    "provider": "ollama",
    "model": "nomic-embed-text"
  },
  "reranker": {
    "name": "free-trial"
  },
  "docs": []
}
```

### Description

open a file give me this error

HTTP 400 Bad Request from http://127.0.0.1:11434/api/generate {"error":"starcoder2:3b does not support insert"}

### To reproduce

open a file (php) and the popup show the 400 error

**Comment by maximilian22x** [comment] 2024-09-30 18:28
I tried to use codestral with my api key from mistral. But autocomplete does not work, no error message, it does not work. 

  "tabAutocompleteModel": {
    "title": "Codestral",
    "provider": "mistral",
    "model": "codestral-latest",
    "apiKey": "mein api key"
  },

**Comment by sestinj** [comment] 2024-10-01 00:03
Thanks all for reporting this! I believe it is a duplicate of https://github.com/continuedev/continue/issues/2421, so I am going to close it in favor of that. We should have a solution soon, but in the meantime reverting to the main release, or an older pre-release, will solve the problem.

I will link this to the other issue for reference

**Closed by sestinj** 2024-10-01 00:03 UTC
Labels: area:autocomplete, kind:bug
