### ISSUE TITLE
Type Error Issue: 'unknown' type in TypeScript

### ISSUE THREAD

**Issue by LangLangBart** [continuedev/continue#582] opened 2023-10-25 14:12 UTC
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 10.15.7
- git commit: f3d1ef79be90335c742fd3e505fd1bfe40b9f402 (main)
- Python 3.11.6
```

### Description

- follow-up: https://github.com/continuedev/continue/pull/581#issuecomment-1778138841
  - creating a ticket to ensure the issue is not forgotten
---

The data type for 'step' was changed from 'Step' to 'Any'. This was done in the file `server/continuedev/core/main.py` with commit a85cb30c.

The most notable symptom of this issue is the 'unknown' type error that is being thrown in several places in the code. 

### To reproduce

```bash

cd server

poetry install && poetry run typegen

cd ../extensions/vscode/

npm run typegen

cd ../../gui/

# tsc
# src/components/StepContainer.tsx:131:34 - error TS2322: Type 'unknown' is not assignable to type 'string'.

# 131           <StyledMarkdownPreview source={props.historyNode.step.description} />
#                                      ~~~~~~

#   src/components/StyledMarkdownPreview.tsx:58:3
#     58   source?: string;
#          ~~~~~~
#     The expected type comes from property 'source' which is declared here on type 'IntrinsicAttributes & StyledMarkdownPreviewProps'

# src/pages/gui.tsx:250:29 - error TS2339: Property 'trim' does not exist on type 'unknown'.

# 250         ].step.description?.trim() === "";
#                                 ~~~~

# src/pages/gui.tsx:650:15 - error TS2322: Type 'unknown' is not assignable to type 'ReactNode'.

# 650               {node.step.name === "User Input" ? (
#                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 651                 node.step.hide || (
#     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ...
# 758                 </TimelineItem>
#     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 759               )}
#     ~~~~~~~~~~~~~~~~

#   node_modules/@types/react/index.d.ts:432:39
#     432     const Fragment: ExoticComponent<{ children?: ReactNode | undefined }>;
#                                               ~~~~~~~~
#     The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & { children?: ReactNode; }'


# Found 3 errors in 2 files.

# Errors  Files
#      1  src/components/StepContainer.tsx:131
#      2  src/pages/gui.tsx:250
```

**Comment by sestinj** [comment] 2023-10-25 23:47
This has been fixed in main. Had to do a workaround for now. Turns out the problem is:
- Pydantic copies models when validating if they don't pass `isinstance`
- Importing a `Step` subclass from `config.py` dynamically with importlib causes `isinstance` not to pass (most likely because the module name for the __bases__ property is different)
- And so to avoid the problems I was seeing with `AnswerQuestionChroma`, I just mapped from the imported class to the original version imported the usual way

But most importantly, we have `step: Step` instead of `step: Any`, which is what caused the build error

**Closed** 2023-10-25 23:47 UTC
Labels: bug
