### ISSUE TITLE
🐞Tool Calling cant unset and causing issues when Using Models without tool support🐞

### ISSUE THREAD

**Issue by nik2048** [continuedev/continue#3396] opened 2024-12-16 08:04 UTC
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [x] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Win 11
- Continue version: latest
- IDE version:
- Model:
- config.json:
{
            "title": "Samba Qwen Coder",
            "provider": "sambanova",
            "model": "Qwen2.5-Coder-32B-Instruct",
            "apiKey": "..."
        },
```

### Description

![image](https://github.com/user-attachments/assets/3d8a9aa7-a786-4094-a4e4-7cf27380028c)

### To reproduce

![image](https://github.com/user-attachments/assets/2e5720fc-5feb-4957-ba13-71f790eb405f)

**Comment by nikhil-swamix** [comment] 2024-12-16 08:07
# related
#3383

**Comment by sestinj** [comment] 2024-12-16 21:50
I think this is a duplicate of another issue, so I'm going close and mention it there

**Closed by sestinj** 2024-12-16 21:50 UTC
Labels: kind:bug, priority:medium, "needs-triage"
