### ISSUE TITLE
Completion instead of Completions

### ISSUE THREAD

**Issue by xaranex1** [continuedev/continue#501] opened 2023-09-23 06:11 UTC
**Describe the bug**

You have bug on line 78 completion instead of completions in llamacpp.py
It will send POST request to bad API endpoint (HTTP ERROR 404)

https://github.com/continuedev/continue/blob/main/continuedev/src/continuedev/libs/llm/llamacpp.py

async def server_generator():
            async with aiohttp.ClientSession(
                connector=aiohttp.TCPConnector(verify_ssl=self.verify_ssl),
                timeout=aiohttp.ClientTimeout(total=self.timeout),
            ) as client_session:
                async with client_session.post(
                    **f"{self.server_url}/completion",**
                    json={"prompt": prompt, "stream": True, **args},
                    headers=headers,
                ) as resp:
                    async for line in resp.content:
                        content = line.decode("utf-8")
                        if content.strip() == "":
                            continue
                        yield json.loads(content[6:])["content"]

**Comment by sestinj** [comment] 2023-09-23 07:13
Thanks for finding this! I'll fix right away and include it in the version I'm releasing tomorrow morning

**Comment by sestinj** [comment] 2023-09-23 07:36
@xaranex1 I took a quick look into this - it seems the problem is actually our documentation...

The LlamaCpp class is made for [this server](https://github.com/ggerganov/llama.cpp/tree/master/examples/server#testing-with-curl), so has a different endpoint name from OpenAI.

This isn't completely obvious from [our documentation](https://continue.dev/docs/reference/Models/llamacpp), so I'll make some improvements there. Could you share which server you are trying to use and maybe I can help get that setup?

**Comment by xaranex1** [comment] 2023-09-23 07:52
I use vast.ai with https://github.com/continuedev/ggml-server-example

**Comment by xaranex1** [comment] 2023-09-23 07:54
And i get error HTTP ERROR 404 on completion because endpoints in llmama cpp python is completions if i go to /docs its okay

**Comment by sestinj** [comment] 2023-09-23 08:23
@xaranex1 Could you try using the [GGML class](https://continue.dev/docs/reference/Models/ggml) and let me know if this works? This is the one that we intended to be used with llama-cpp-python, though of course this naming is a bit backward

**Comment by xaranex1** [comment] 2023-09-23 09:54
Yes it works! Thanks a lot!

**Comment by sestinj** [comment] 2023-09-23 17:03
Fantastic! I'll close the issue, but let me know if you have any other issues : ) Can ask in [Discord](https://discord.gg/NWtdYexhMs) if that's ever easier

I'll also rename the GGML class probably to avoid this confusion

**Closed by sestinj** 2023-09-23 17:03 UTC
