### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by davesawatzky** [continuedev/continue#468] opened 2023-09-12 17:22 UTC
**Describe the bug**
On starting VSCode, the Continue server is stuck in a loading state.  However, if I go to the .continue/server/exe directory and run the server directly in the terminal, it seems to start just fine and then the VSCode extension finally works.  The same thing happens after removing the .continue directories and reinstalling the extension.

**To Reproduce**
Simply start the extension.

**Environment**

- Windows 10
- Python Version: [e.g. 3.11.5]
- Continue Version: [e.g. v0.0.382]

Screenshot of the server attempting to start
![Screenshot 2023-09-12 120354](https://github.com/continuedev/continue/assets/76271425/212932c5-4bbb-45e0-aa19-5d7a82d69ca5)

Screenshot of the terminal screen with the server running after manual start
![Screenshot 2023-09-12 121016](https://github.com/continuedev/continue/assets/76271425/a07f1969-e629-4e5e-8dbc-703c02f78694)

This log was created after starting the server manually through the terminal.  This was also a fresh install.
![Screenshot 2023-09-12 122432](https://github.com/continuedev/continue/assets/76271425/12877496-ac70-4816-b9d7-4b02dabd1aa2)

**Comment by sestinj** [comment] 2023-09-12 17:29
Looks like the problem is a failure to kill the previous server possibly. I wonder whether stopping the manually running server and then restarting VS Code would allow it to start?

The typical reason for EBUSY is either a) the binary was just downloaded, and is attempted to be run too soon after (not yet let go by the writing process), or b) the binary is already being run. It seems like the second problem is happening here, because we are already retrying after waiting for a

**Comment by davesawatzky** [comment] 2023-09-12 17:43
I killed the server in the terminal and restarted VSCode twice just now.  Each time there's a popup indicating that the continue server is being installed.  After waiting for everything to be initialized and the the extensions loaded I tried the extension again and all I get is the starting spinner.

**Comment by sestinj** [comment] 2023-09-12 19:08
Solution a) is to just run it manually, and then in VS Code settings there is a checkbox you should check titled "Manually Running Server" (can search 'continue' in settings to find it). This will stop Continue from trying to kill and re-download the binary each time. And another easier way to run the server might be `pip install continuedev && python -m continuedev` if you'd like a nice short terminal command that also lets you update with `pip install --upgrade continuedev`.

For the real solution, I'm going to have to dig into why we're failing to kill the previous server, or where the EBUSY error is coming from. I don't really expect anything, but is there anything that might stand out as potentially relevant about your computer's environment? e.g. running WSL, special file permissions restrictions, security software, etc.

**Comment by davesawatzky** [comment] 2023-09-12 20:03
Thanks for the reply.  No, I don't think I have anything special loaded up, other than other vscode extensions.  I'm not using wsl and access rights aren't an issue.  Could there be a conflict with another extension?  I develop with Vue quite heavily and run the volar extension among a number of other things.  Continue has worked fine for me up until a few days ago, and I can't think of anything that's changed.

**Comment by davesawatzky** [comment] 2023-09-12 21:17
Alright.  I did a lot more sleuthing.  It turns out it was my Bitdefender AV.  It was flagging the Continue server as an 'Infected Web Resource' for the last week and blocking it - but only from vscode and not the terminal.  I had to include an exception in Bitdefender and now it runs fine.  Crazy.

**Comment by sestinj** [comment] 2023-09-12 21:19
Woah ok that's fascinating. I think in the long run we need to find a method of installation that does't cause issues like this to occur. Until then we can at least make the messaging much more clear when thing fail.

Gonna keep the issue open until I've fully updated troubleshooting docs, thanks for digging into this

**Comment by erlebach** [comment] 2023-09-13 23:12
Question: is llama.cpp/server and Visual Studio Code running on the same machine?  If true, could you email me `.continue/config.py`?
I am running the remote explorer in Visual Studio Code, so VSC is running on the same server as llama.cpp. Unfortunately, the $HOME/.continue/ folder was not created. Why would that be? It is only created on my local machine even though the extension seems to be installed on the remote machine. Thanks.

**Comment by sestinj** [comment] 2023-09-15 06:00
Hi @erlebach, sorry I'm just seeing this comment. It looks like you've figured this out in the other issue, but let me know if not.

llama.cpp can run either on the same machine or elsewhere. ~/.continue would be created on whichever machine where the extension is installed

**Comment by sestinj** [comment] 2023-09-25 20:48
Going to close this issue since we now have much more detailed docs on how to run the server manually if needed. Thanks Dave for digging so deeply into this!

**Closed by sestinj** 2023-09-25 20:48 UTC
