### ISSUE TITLE
Continue does not /edit remote VS Code files

### ISSUE THREAD

**Issue by lonestriker** [continuedev/continue#412] opened 2023-08-27 05:01 UTC
**Is your feature request related to a problem? Please describe.**
I use VS Code to remotely access my Linux server from my Windows PC via ssh.  VS Code runs on Windows.  When I use `/edit <prompt>` on a local Windows file, it works as expected. If I am connected remotely, Continue tries to access the file locally.  For example, if I open `/home/ubuntu/app.py` on Linux, Continue tries to write to Windows `\home\ubuntu\app.py` instead.

**Describe the solution you'd like**
Support for VS Code remote sessions.

**Describe alternatives you've considered**
None.

**Additional context**
VS Code remote is in common use by developers. In general, Linux is where a lot of code is run and debugged. But Windows (or Mac) are the general desktops.

**Comment by sestinj** [comment] 2023-08-27 05:05
Looking into this now. What version of Continue are you using?

**Comment by lonestriker** [comment] 2023-08-27 05:08
Wow, thanks for the fast reply. Just installed so I'm assuming it's the latest version: v0.0.333

**Comment by sestinj** [comment] 2023-08-27 05:12
Great! Already reproduced myself on an EC2. Def a bug : ( I'll let you know soon if there's a fix

**Comment by sestinj** [comment] 2023-08-27 05:14
Were you seeing `The file <FILEPATH> does not exist. Please save it first.`? Quick fix if so

**Comment by lonestriker** [comment] 2023-08-27 05:15
Yes, that's the error

**Comment by lonestriker** [comment] 2023-08-27 07:03
Still getting the error with version `0.0.335`.  It's still retaining the Windows file path separator, but the file itself is the right remote path (if you replace `\` with `/`):

`The file \home\ubuntu\git\scratchpad\app.py does not exist. Please save it first.`

**Comment by sestinj** [comment] 2023-08-27 07:27
Yeah, v0.0.335 got through one layer of the problem, but this ended up slightly deeper than I originally thought. Most everything seems solved, just working on setting up an SSH env to test.

**Comment by sestinj** [comment] 2023-08-27 09:55
I'm going to wrap this up tomorrow—sorry for taking longer after announcing "quick fix". vs code has some odd behavior when it comes to SSH...

**Comment by lonestriker** [comment] 2023-08-27 10:52
A fix in less than a day is astounding! It's not like we get paid to fix open source software :)  Thanks much for your attention.

**Comment by A-De-Almeida** [comment] 2023-08-27 13:41
The same issue occurs when using VS Code with Windows Subsystem for Linux (WSL).

**Comment by sestinj** [comment] 2023-08-27 18:24
@A-De-Almeida Makes sense—VS Code uses a similar URI encoding scheme for SSH/WSL. Getting back to working on this now

**Comment by sestinj** [comment] 2023-08-28 01:46
@A-De-Almeida @lonestriker Finally got it!

There's a small chance you'll need to uninstall Continue, quit VS Code, then restart and redownload. At first, I dowloaded the new version and it was only updating in my non-SSH windows. Either something odd about how VS Code updates extensions, or I was just mistaken in thinking I had updated. Regardless, I'm now able to /edit on remote SSH

**Comment by A-De-Almeida** [comment] 2023-08-28 08:19
@sestinj I get this error when trying to edit the file in wsl
![image](https://github.com/continuedev/continue/assets/109695829/c905b48d-7a11-4c7f-b393-a35c0638751c)

**Comment by lonestriker** [comment] 2023-08-28 19:52
> 

Not having much luck. I've tried uninstalling Continue, exiting VS Code, starting VS Code, and installing Continue.  Still get the wrong path separators for my remote file; `\home\ubuntu\blah.py`  instead of `/home/ubuntu/blah.py`.

I also seem to be getting the `/edit` command repeated in my prompt, even though I've only specified it once:
```
/edit /edit write hello world in python
```

**Comment by sestinj** [comment] 2023-08-28 20:36
ok, was able to reproduce, know the source of the error. Have to attend to something else, but will have a push fixed later today

**Comment by sestinj** [comment] 2023-08-28 22:05
@lonestriker @A-De-Almeida Solution is ready in the latest version. I was able to setup WSL on my own Windows machine and verify that it works there, so with higher confidence the fix is for real this time.

**Comment by lonestriker** [comment] 2023-08-29 05:00
> ok, was able to reproduce, know the source of the error. Have to attend to something else, but will have a push fixed later today

I was able to get it to work remotely finally. The issue was that the old Continue Server was still up and running, even when upgrading the plugin, even after VS Code was closed.  You either have to reboot or manually kill the run.exe process that is spawned.

To get a full clean Continue uninstall/install, you need to:
* Uninstall Continue
* Close VS Code
* Kill any remaining run.exe processes (on Windows) or just reboot
* Remove the $HOME/.continue directory
* Start VS Code
* Install Continue clean

Thanks for the fix!

**Comment by sestinj** [comment] 2023-08-29 06:12
Ah this might explain a few other things. Must be a windows only issue.

Going to close this issue now that it's resolved, but will create another for the failure to kill the old server

**Comment by godimarcovr** [comment] 2023-09-04 11:00
Hello, thanks for this great extension!
This is not solved for me even after updating and reinstalling everything.
I have vscode running with the Continue extension running on my Windows laptop. When I open local folders, everything works. When I use Remote SSH on my Linux server, the /edit diff doesn't appear, only the Question Answering works in the side chat.
I get this error from the logs:
Unable to read file '\home\<myname>\code\...\name_of_current_file.py' (Error: Unable to resolve nonexistent file).

Maybe it's some path separator error? I see backslashes on this linux path.
If it helps I have more info: I'm currently running the Continue server manually because it doesn't start automatically for me. I'm running a llama-cpp server with my own model.
Like I said everything works on local folders, but it doesn't show a diff panel on Remote SSH, only normal QA works.

**Comment by sestinj** [comment] 2023-09-04 15:14
@godimarcovr definitely the path separator bug again - let me check this out today and get back with you, I think I know where to look

**Comment by sestinj** [comment] 2023-09-04 16:15
@godimarcovr Just published an update, was a quick fix. Let me know if for some reason the problem persists

**Comment by sestinj** [comment] 2023-09-05 15:57
@godimarcovr this would explain someone else's issue too! In the meantime the shortcuts (cmd+shift+enter/backspace) should work to accept or reject, but I'll get this fixed today

**Comment by sestinj** [comment] 2023-09-10 18:51
This turned out to be less of an obvious fix than I expected. It seems that there are [existing issues](https://google.com/search?q=vscode+not+displaying+codelens) around VS Code failing to display Code Lens, so I'm trying to determine whether this is the problem or not.

**Comment by erlebach** [comment] 2023-09-15 00:59
What is the command to start the server manually? Is it: 
```
python config.py
```
where `config.py` is in $HOME/.continue? Thanks.

**Comment by sestinj** [comment] 2023-09-15 01:29
Hi @erlebach, you can use the following:

1. `pip install continuedev` (if you need to upgrade the version, you can `pip install --upgrade continuedev`)
2. `python -m continuedev`

Documentation is [here](https://continue.dev/docs/walkthroughs/manually-run-continue#recommended-use-the-continuedev-pypi-package). Looks from the other issue like you got this figured out though : )

**Comment by sestinj** [comment] 2023-09-15 05:56
Hi @godimarcovr, I'm going to close this issue and refer to a duplicate, since things are becoming a bit cluttered: https://github.com/continuedev/continue/issues/436

**Closed by sestinj** 2023-09-15 05:56 UTC
