### ISSUE TITLE
When using multiple @Files, only one of them is given as context to the LLM

### ISSUE THREAD

**Issue by tijszwinkels** [continuedev/continue#1464] opened 2024-06-11 06:11 UTC
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS 14.5
- Continue: 0.9.155 (prerelease)
- IDE: 1.89.1
```

### Description

When using multiple @Files (+search for filenames) with Continuedev, only one of these is given as context to the LLM. The other ones have `[object Object]` as context. For example:

```we-want.json
[object Object]
```

See screenshot.

<img width="1213" alt="Screenshot 2024-06-11 at 08 00 03" src="https://github.com/continuedev/continue/assets/140654/cd7ba298-502b-4557-ba78-3957777fb84f">

### To reproduce

1. Open chat (cmd-L)
2. Add multiple files as context with @File
3. Send request
4. Notice that the LLM can answer questions about only one of these files.

### Log output

```Shell
==========================================================================
==========================================================================
Settings:
contextLength: 4096
model: pillar/codestral
maxTokens: 1024
log: undefined

############################################

<user>
/test/java/nl/rws/dso/apim/analytics/JsonTransformUtilitiesTest.java
// src/test/java/nl/rws/dso/apim/analytics/JsonTransformUtilitiesTest.java
package nl.rws.dso.apim.analytics;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonPrimitive;
import org.junit.Test;

import java.util.Map;
import java.util.Set;

import static org.junit.Assert.*;

public class JsonTransformUtilitiesTest {

      <...> // Cut out the actual file contents, but they are there!
}




```we-want.json
[object Object]
```

JsonTransformUtilitiesTest.java we-want.json What are these files?

==========================================================================
==========================================================================
Completion:

 The given text includes two parts: `JsonTransformUtilitiesTest.java` and a `we-want.json` file.

1. `JsonTransformUtilitiesTest.java` is a Java test class that tests the methods of a hypothetical `JsonTransformUtilities` class which, based on its name, might be a utility library for transforming JSON objects. This class contains multiple JUnit tests that verify the functionality of different transformation operations like renaming fields, retaining specific fields, adding new fields, and transforming JSON with a combination of these operations.

2. `we-want.json` is a file that is expected as output by one or more of the tests in the Java test class. However, without the actual content of this file, we cannot determine what its purpose or contents are exactly. It seems to be mentioned in a comment within the test class, where it suggests printing an object and comparing it to the contents of this JSON file. But since we do not have that JSON file's contents, we cannot confirm if that is indeed the case.

To provide further assistance, I would need more context or the actual content of the `we-want.json` file.
```

**Comment by sestinj** [comment] 2024-06-12 04:21
@tijszwinkels it looks like this is probably a duplicate of https://github.com/continuedev/continue/issues/1392

**Comment by tijszwinkels** [comment] 2024-06-12 20:59
Yes, agreed. I didn't notice before that it only happens with .json files.

**Comment by tijszwinkels** [comment] 2024-06-12 21:40
So I'm pretty sure the problem is in IdeMessenger.ts:

```
  private _safeParseResponse(data: any) {
    // This causes .json files to be parsed as objects instead of remaining strings
    let responseData = data ?? null;
    try {
      responseData = JSON.parse(responseData);
    } catch {}
    return responseData;
  }
```

**Comment by sestinj** [comment] 2024-06-13 00:07
@tijszwinkels yes you absolutely found it. I just made a fix: https://github.com/continuedev/continue/commit/e2a90ae521dd177353274cf8582f63915b5de6b1

This was known but I guess I'd decided that before making a change to something so fundamental I'd be safe for a minute. Checked and everything is already deserialized on the way over to the webview

**Comment by sestinj** [comment] 2024-06-13 00:07
The "safe" meaning was just so that we didn't try to parse something that was undefined. `null` can be parsed by JSON.parse, but `undefined` will fail

**Comment by sestinj** [comment] 2024-06-13 00:08
Going to close as this will be in a pre-release in just a minute!

**Closed by sestinj** 2024-06-13 00:08 UTC
Labels: bug

**Comment by dandv** [comment] 2024-07-02 20:16
I see this issue with only one file, `package.json`, in the JetBrains 0.0.50 extension:

![image](https://github.com/continuedev/continue/assets/33569/d9d9ad8a-369b-4723-b813-ba7df6665938)
