### ISSUE TITLE
"No module named 'continuedev'" error

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#308] opened 2023-07-27 16:34 UTC
This issue was reported by two users: 
- @AymericG https://github.com/continuedev/continue/issues/300#issuecomment-1652891100
- @tom-voicer https://github.com/continuedev/continue/issues/300#issuecomment-1653192021

**Comment by TyDunn** [comment] 2023-07-27 16:35
Are you able to tell us more about your situation? For example:
- Operating System: [e.g. MacOS]
- Python Version: [e.g. 3.10.6]
- Continue Version: [e.g. v0.0.207]

This would help us debug this problem!

**Comment by 117649** [comment] 2023-07-31 13:01
I have this problem.
I'm on win10 and installed python 3.11 from MS store.

**Comment by sestinj** [comment] 2023-07-31 21:24
@117649 looking into this currently, and I believe we will be able to solve it and many other issues by bundling the Python server. You can track that work [here](https://github.com/continuedev/continue/issues/320), and I'll also comment on this issue once done (later today is the goal).

**Comment by 117649** [comment] 2023-08-01 04:37
I've got passed this by manually install python requirements as suggested by other post.

**Comment by sestinj** [comment] 2023-08-03 08:46
@117649 Glad that fixed it! Closing this issue as the root cause has also been fixed with #320

**Closed by sestinj** 2023-08-03 08:46 UTC
Labels: bug
