### ISSUE TITLE
Build from source detected as Agent.Spyware.Stealer.DDS

### ISSUE THREAD

**Issue by Eforen** [continuedev/continue#525] opened 2023-09-30 18:54 UTC
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows - Malwarebytes Premium
- Continue: Built from verified source from GH
```

### Description

Built fine but when I tried to run it Malwarebytes claimed it was a `Agent.Spyware.Stealer.DDS` and quarintined it. I didn't see anything sus when I audited it before building and running it but this is concerning.

### To reproduce

1. Git Clone from GH
2. build via `./build.cmd`
3. Rename `run.exe` to `Continue-Server.exe`
4. Run it
5. Malwarebytes Premium deletes it.

### Log output

```Shell
[Hybrid-Analysys results](https://www.hybrid-analysis.com/sample/7b5646868958410ecc35b4c1c8c85ce23961f4fd3c795f5d82dfd5587297ef3d)
[VirusTotal 12/71](https://www.virustotal.com/gui/file-analysis/MDllZWQ2YzhhM2EzZWY5NDMzZDJmMWQ2YjJhZTg5M2Q6MTY5NjA5OTc0OQ==)
```

**Comment by sestinj** [comment] 2023-09-30 19:06
There's an instructive thread [here](https://stackoverflow.com/questions/64788656/exe-file-made-with-pyinstaller-being-reported-as-a-virus-threat-by-windows-defen) on StackOverflow. Most likely for similar reasons (potential to make outbound calls to OpenAI, and pyinstaller creates a temp folder) Continue is being flagged. There are likely methods of getting around the defender, as suggested in the post or otherwise, but I feel that this would only serve to add a layer of distrust.

My official recommendation would be to instead use the PyPI package to run the server (`pip install continuedev && python -m continuedev`). Or is there reason why you require a binary?

**Comment by Eforen** [comment] 2023-10-02 23:42
@sestinj its more about the from source part then the from binary part. I am a bit of a spook so I like to audit the code I run on my computer where posible.

**Comment by sestinj** [comment] 2023-10-02 23:44
@Eforen this makes sense! Best option might be to follow the development setup [here](https://github.com/continuedev/continue/blob/main/CONTRIBUTING.md#environment-setup)

That way you are running directly from source without having to build a binary

**Comment by Eforen** [comment] 2023-10-03 12:50
I tried that last night however I am sorry I got busy and didn't post the error but it was complaining about some isaclass function. I even tried running the pip version as per the instructions and that version says it is a module and has no __main__ function and this can't start.

**Comment by Eforen** [comment] 2023-10-03 12:51
I'll post errors when I am back from work

**Comment by Eforen** [comment] 2023-10-04 03:27
@sestinj as promised

Install
```py
(env) REDACTED\continue>pip install -r continuedev\requirements.txt
Collecting fastapi==0.95.1
  Using cached fastapi-0.95.1-py3-none-any.whl (56 kB)
Collecting typer==0.7.0
  Using cached typer-0.7.0-py3-none-any.whl (38 kB)
Collecting openai==0.27.5
  Using cached openai-0.27.5-py3-none-any.whl (71 kB)
Collecting boltons==23.0.0
  Using cached boltons-23.0.0-py2.py3-none-any.whl (194 kB)
Collecting pydantic==1.10.7
  Using cached pydantic-1.10.7-cp39-cp39-win_amd64.whl (2.2 MB)
Collecting uvicorn==0.21.1
  Using cached uvicorn-0.21.1-py3-none-any.whl (57 kB)
Collecting python-dotenv==1.0.0
  Using cached python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting nest-asyncio==1.5.6
  Using cached nest_asyncio-1.5.6-py3-none-any.whl (5.2 kB)
Collecting websockets==11.0.2
  Using cached websockets-11.0.2-cp39-cp39-win_amd64.whl (124 kB)
Collecting urllib3==1.26.15
  Using cached urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Collecting posthog==3.0.1
  Using cached posthog-3.0.1-py2.py3-none-any.whl (37 kB)
Collecting tiktoken==0.4.0
  Using cached tiktoken-0.4.0-cp39-cp39-win_amd64.whl (635 kB)
Collecting jsonref==1.1.0
  Using cached jsonref-1.1.0-py3-none-any.whl (9.4 kB)
Collecting jsonschema==4.17.3
  Using cached jsonschema-4.17.3-py3-none-any.whl (90 kB)
Collecting directory-tree==0.0.3.1
  Using cached directory_tree-0.0.3.1-py3-none-any.whl (17 kB)
Collecting anthropic==0.3.4
  Using cached anthropic-0.3.4-py3-none-any.whl (793 kB)
Collecting chevron==0.14.0
  Using cached chevron-0.14.0-py3-none-any.whl (11 kB)
Collecting psutil==5.9.5
  Using cached psutil-5.9.5-cp36-abi3-win_amd64.whl (255 kB)
Collecting pygithub==1.59.0
  Using cached PyGithub-1.59.0-py3-none-any.whl (342 kB)
Collecting meilisearch-python-async==1.4.8
  Using cached meilisearch_python_async-1.4.8-py3-none-any.whl (27 kB)
Collecting socksio==1.0.0
  Using cached socksio-1.0.0-py3-none-any.whl (12 kB)
Collecting ripgrepy==2.0.0
  Using cached ripgrepy-2.0.0.tar.gz (19 kB)
Collecting replicate==0.11.0
  Using cached replicate-0.11.0-py3-none-any.whl (22 kB)
Collecting bs4==0.0.1
  Using cached bs4-0.0.1.tar.gz (1.1 kB)
Collecting redbaron==0.9.2
  Using cached redbaron-0.9.2-py2.py3-none-any.whl (34 kB)
Collecting python-lsp-server[websockets]==1.8.0
  Using cached python_lsp_server-1.8.0-py3-none-any.whl (73 kB)
Collecting huggingface-hub==0.16.4
  Using cached huggingface_hub-0.16.4-py3-none-any.whl (268 kB)
Collecting starlette<0.27.0,>=0.26.1
  Using cached starlette-0.26.1-py3-none-any.whl (66 kB)
Collecting click<9.0.0,>=7.1.1
  Using cached click-8.1.7-py3-none-any.whl (97 kB)
Collecting aiohttp
  Using cached aiohttp-3.8.5-cp39-cp39-win_amd64.whl (327 kB)
Collecting tqdm
  Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Collecting requests>=2.20
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting typing-extensions>=4.2.0
  Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Collecting h11>=0.8
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Collecting backoff>=1.10.0
  Using cached backoff-2.2.1-py3-none-any.whl (15 kB)
Collecting monotonic>=1.5
  Using cached monotonic-1.6-py2.py3-none-any.whl (8.2 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting python-dateutil>2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting regex>=2022.1.18
  Using cached regex-2023.10.3-cp39-cp39-win_amd64.whl (269 kB)
Collecting attrs>=17.4.0
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Using cached pyrsistent-0.19.3-cp39-cp39-win_amd64.whl (62 kB)
Collecting distro<2,>=1.7.0
  Using cached distro-1.8.0-py3-none-any.whl (20 kB)
Collecting httpx<1,>=0.23.0
  Using cached httpx-0.25.0-py3-none-any.whl (75 kB)
Collecting tokenizers>=0.13.0
  Using cached tokenizers-0.14.0-cp39-none-win_amd64.whl (2.2 MB)
Collecting anyio<4,>=3.5.0
  Using cached anyio-3.7.1-py3-none-any.whl (80 kB)
Collecting pyjwt[crypto]>=2.4.0
  Using cached PyJWT-2.8.0-py3-none-any.whl (22 kB)
Collecting deprecated
  Using cached Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
Collecting pynacl>=1.4.0
  Using cached PyNaCl-1.5.0-cp36-abi3-win_amd64.whl (212 kB)
Collecting camel-converter>=1.0.0
  Using cached camel_converter-3.0.3-py3-none-any.whl (5.5 kB)
Collecting aiofiles>=0.7
  Using cached aiofiles-23.2.1-py3-none-any.whl (15 kB)
Collecting packaging
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
Collecting baron>=0.7
  Using cached baron-0.10.1-py2.py3-none-any.whl (45 kB)
Collecting pluggy>=1.0.0
  Using cached pluggy-1.3.0-py3-none-any.whl (18 kB)
Collecting jedi<0.20.0,>=0.17.2
  Using cached jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
Collecting ujson>=3.0.0
  Using cached ujson-5.8.0-cp39-cp39-win_amd64.whl (42 kB)
Collecting python-lsp-jsonrpc<2.0.0,>=1.1.0
  Using cached python_lsp_jsonrpc-1.1.2-py3-none-any.whl (8.8 kB)
Collecting docstring-to-markdown
  Using cached docstring_to_markdown-0.12-py3-none-any.whl (18 kB)
Collecting importlib-metadata>=4.8.3
  Using cached importlib_metadata-6.8.0-py3-none-any.whl (22 kB)
Collecting pyyaml>=5.1
  Using cached PyYAML-6.0.1-cp39-cp39-win_amd64.whl (152 kB)
Collecting fsspec
  Using cached fsspec-2023.9.2-py3-none-any.whl (173 kB)
Collecting filelock
  Using cached filelock-3.12.4-py3-none-any.whl (11 kB)
Collecting exceptiongroup
  Using cached exceptiongroup-1.1.3-py3-none-any.whl (14 kB)
Collecting idna>=2.8
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting sniffio>=1.1
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting rply
  Using cached rply-0.7.8-py2.py3-none-any.whl (16 kB)
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting httpcore<0.19.0,>=0.18.0
  Using cached httpcore-0.18.0-py3-none-any.whl (76 kB)
Collecting certifi
  Using cached certifi-2023.7.22-py3-none-any.whl (158 kB)
Collecting zipp>=0.5
  Using cached zipp-3.17.0-py3-none-any.whl (7.4 kB)
Collecting parso<0.9.0,>=0.8.3
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting cryptography>=3.4.0
  Using cached cryptography-41.0.4-cp37-abi3-win_amd64.whl (2.7 MB)
Collecting cffi>=1.12
  Using cached cffi-1.16.0-cp39-cp39-win_amd64.whl (181 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.0-cp39-cp39-win_amd64.whl (98 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.9.2-cp39-cp39-win_amd64.whl (61 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.4.0-cp39-cp39-win_amd64.whl (44 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.4-cp39-cp39-win_amd64.whl (28 kB)
Collecting soupsieve>1.2
  Using cached soupsieve-2.5-py3-none-any.whl (36 kB)
Collecting wrapt<2,>=1.10
  Using cached wrapt-1.15.0-cp39-cp39-win_amd64.whl (36 kB)
Collecting appdirs
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Using legacy 'setup.py install' for ripgrepy, since package 'wheel' is not installed.
Using legacy 'setup.py install' for bs4, since package 'wheel' is not installed.
Installing collected packages: urllib3, sniffio, pycparser, idna, exceptiongroup, colorama, charset-normalizer, certifi, zipp, ujson, typing-extensions, tqdm, requests, pyyaml, parso, packaging, multidict, h11, fsspec, frozenlist, filelock, cffi, appdirs, anyio, yarl, wrapt, soupsieve, six, rply, python-lsp-jsonrpc, pyjwt, pluggy, jedi, importlib-metadata, huggingface-hub, httpcore, docstring-to-markdown, cryptography, attrs, async-timeout, aiosignal, websockets, tokenizers, starlette, regex, python-lsp-server, python-dateutil, pyrsistent, pynacl, pydantic, monotonic, httpx, distro, deprecated, click, camel-converter, beautifulsoup4, baron, backoff, aiohttp, aiofiles, uvicorn, typer, tiktoken, socksio, ripgrepy, replicate, redbaron, python-dotenv, pygithub, psutil, posthog, openai, nest-asyncio, meilisearch-python-async, jsonschema, jsonref, fastapi, directory-tree, chevron, bs4, boltons, anthropic
    Running setup.py install for ripgrepy ... done
    Running setup.py install for bs4 ... done
Successfully installed aiofiles-23.2.1 aiohttp-3.8.5 aiosignal-1.3.1 anthropic-0.3.4 anyio-3.7.1 appdirs-1.4.4 async-timeout-4.0.3 attrs-23.1.0 backoff-2.2.1 baron-0.10.1 beautifulsoup4-4.12.2 boltons-23.0.0 bs4-0.0.1 camel-converter-3.0.3 certifi-2023.7.22 cffi-1.16.0 charset-normalizer-3.3.0 chevron-0.14.0 click-8.1.7 colorama-0.4.6 cryptography-41.0.4 deprecated-1.2.14 directory-tree-0.0.3.1 distro-1.8.0 docstring-to-markdown-0.12 exceptiongroup-1.1.3 fastapi-0.95.1 filelock-3.12.4 frozenlist-1.4.0 fsspec-2023.9.2 h11-0.14.0 httpcore-0.18.0 httpx-0.25.0 huggingface-hub-0.16.4 idna-3.4 importlib-metadata-6.8.0 jedi-0.19.1 jsonref-1.1.0 jsonschema-4.17.3 meilisearch-python-async-1.4.8 monotonic-1.6 multidict-6.0.4 nest-asyncio-1.5.6 openai-0.27.5 packaging-23.2 parso-0.8.3 pluggy-1.3.0 posthog-3.0.1 psutil-5.9.5 pycparser-2.21 pydantic-1.10.7 pygithub-1.59.0 pyjwt-2.8.0 pynacl-1.5.0 pyrsistent-0.19.3 python-dateutil-2.8.2 python-dotenv-1.0.0 python-lsp-jsonrpc-1.1.2 python-lsp-server-1.8.0 pyyaml-6.0.1 redbaron-0.9.2 regex-2023.10.3 replicate-0.11.0 requests-2.31.0 ripgrepy-2.0.0 rply-0.7.8 six-1.16.0 sniffio-1.3.0 socksio-1.0.0 soupsieve-2.5 starlette-0.26.1 tiktoken-0.4.0 tokenizers-0.14.0 tqdm-4.66.1 typer-0.7.0 typing-extensions-4.8.0 ujson-5.8.0 urllib3-1.26.15 uvicorn-0.21.1 websockets-11.0.2 wrapt-1.15.0 yarl-1.9.2 zipp-3.17.0
```

Run
```py
(env) REDACTED\continue>python run.py
Traceback (most recent call last):
  File "REDACTED\continue\run.py", line 4, in <module>
    from continuedev.main import main
  File "REDACTED\continue\continuedev\main.py", line 1, in <module>
    from .src.continuedev.server.main import run_server
  File "REDACTED\continue\continuedev\src\continuedev\__init__.py", line 4, in <module>
    from .core.config import ContinueConfig
  File "REDACTED\continue\continuedev\src\continuedev\core\config.py", line 5, in <module>
    from ..libs.llm.openai_free_trial import OpenAIFreeTrial
  File "REDACTED\continue\continuedev\src\continuedev\libs\llm\__init__.py", line 8, in <module>
    from ...core.main import ChatMessage
  File "REDACTED\continue\continuedev\src\continuedev\core\main.py", line 18, in <module>
    class ChatMessage(ContinueBaseModel):
  File "pydantic\main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "REDACTED_ROOT\Python39\lib\typing.py", line 847, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

Precompiled
```py
(env) REDACTED\continue>python -m continuedev
REDACTED\continue\env\Scripts\python.exe: No module named continuedev.__main__; 'continuedev' is a package and cannot be directly executed

```

**Comment by sestinj** [comment] 2023-10-04 04:32
@Eforen Instead of `python -m continuedev` you would probably want to do `python -m continuedev.src.continuedev` (a matter of folder structure that will soon be sorted out)

But this will probably show the error from above still. My guess is that the problem is either the Literal or the Union[str, None] in the ChatMessage class in core/main.py. If you change them to `str` and `Optional[str]` respectively and find that this fixes the issue I'll push this as an official update right away

**Comment by sestinj** [comment] 2023-10-12 18:14
@Eforen I setup a container with python 3.9 and made it through all of the errors I found, this one included (was solved by an upgrade to pydantic version).

This is also available as a new PyPI version, 0.1.51

**Comment by Eforen** [comment] 2023-10-14 00:16
Cool I'll try it out

**Comment by Eforen** [comment] 2023-10-17 01:02
Wait what version of python should I be using it sounds like 3.9 is not the one I should be using.
Also maybe making a dockerfile for this would help with all the issues people are running into. And if its just a relay to connect to the api for openai etc for the most part then does it really need to be running on the user's computer at all...

**Comment by sestinj** [comment] 2023-10-17 03:10
We use 3.10.8 for the builds if you're willing to use just any version.

The reason for the server is a bit more than just a relay - it handles most logic, including prompting, calculating embeddings, configuration, state management, etc... which is why we want it to be on-device

Docker is not a bad idea though - we've been thinking about this

**Comment by sestinj** [comment] 2023-11-17 00:25
@Eforen I wanted to check in on this - have you been able to get Continue setup?

**Comment by sestinj** [comment] 2023-12-28 03:24
@Eforen We've now completely removed the need for the Continue Python server, which means that there is no need for building the binary at all. I think it's best to close this particular issue, but please open another if separate problems show up

**Closed by sestinj** 2023-12-28 03:24 UTC
Labels: bug
