### ISSUE TITLE
Cannot read properties of undefined (reading 'viewType')

### ISSUE THREAD

**Issue by pjv** [continuedev/continue#923] opened 2024-03-03 13:43 UTC
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 13.6.4
- Continue: 0.9.76
- IDE: VSCodium 1.87.0
```

### Description

After updating continue from 0.9.71 to .76, i get the error in the title whenever i try to `command-L` any code into context.

The dev console is completely empty.

I saw the note in the troubleshooting guide about node v 19. In about VSCodium for the version I'm running (which is latest), it says `Node.js: 18.17.1`. Could this be the reason?

**Comment by TheLapinMalin** [comment] 2024-03-03 15:02
Looks like the same issue I've reported here: https://github.com/continuedev/continue/issues/915

And also running NodeJS 18.17.1.

**Comment by pjv** [comment] 2024-03-03 15:07
@TheLapinMalin it does look the same.

interestingly, I am only seeing this issue on my desktop which is an intel mac. On my laptop which is Apple Silicon M2, but running identical version numbers of everything from macOS to VSCodium, node, continue extension... it works perfectly.

**Comment by shibeta** [comment] 2024-03-03 15:18
I got same unexpected behavior. I downgrade to v0.8.14 and it seems everything works fine. 
### Relevant environment info ###
```
- OS: Windows 11 Professional 22H2 10.0.22621
- Continue: v0.9.76 (pre-release)
- IDE: vscode 1.87.0 (system setup)
  - Electron: 27.3.2
  - Chromium: 118.0.5993.159
  - Node.js: 18.17.1
  - V8: 11.8.172.18-electron.0
```
### Description ###
Usually When I press `ctrl + L` or `ctrl + shift + L` in editor, a dialog box showed to input prompt. today, what I got is a warning toast `Cannot read properties of undefined (reading 'viewType')` , then no dialog box showed, and nothing happened.
###  Log output ###
```
No log output at all, strangely.
```

**Comment by sestinj** [comment] 2024-03-03 21:12
@pjv @shibeta @TheLapinMalin This should now be fixed in the latest. There was only one place in our code where a property called viewType as accessed, so it ended up being a single character fix: https://github.com/continuedev/continue/blob/8fb55eca2574c3630d456dbc0136e581d28b4f5d/extensions/vscode/src/commands.ts#L19

**Comment by TheLapinMalin** [comment] 2024-03-03 21:25
Yes, looks good now! Thanks for the quick fix. :)

**Comment by pjv** [comment] 2024-03-03 21:42
@sestinj Thanks! Glad I’m not the only one who works on weekends. 😄

**Closed** 2024-03-03 21:42 UTC
Labels: bug
