### ISSUE TITLE
/edit does not do anything with Ollama v0.0.21

### ISSUE THREAD

**Issue by cheuk-cheng** [continuedev/continue#509] opened 2023-09-24 17:12 UTC
**Describe the bug**
Entering "/edit ..." as suggested in continue's quick tutorial does nothing.  continue works when I do not use "/edit".

**To Reproduce**
1. Highlight the following code in Visual Studio Code editor
```
names = ['red', 'green', 'blue']

def print_names(names):
    for index in range(len(names)+1):
        print(names[index])

print_names(names)
```
2. Press cmd+shift+M to select the code
3. Request an edit by entering "/edit Optimize this Python code" (without quotes) and click "CONTINUE" button
4. No output from continue and there is no log to view 

**Environment**

- Operating System: MacOS 
- Python Version: 3.10.11
- Continue Version: v0.0.397
- Ollama v0.0.21

**Logs**
None

```
REPLACE THIS SECTION WITH CONSOLE LOGS OR A SCREENSHOT...
```

To get the Continue server logs:

1. cmd+shift+p (MacOS) / ctrl+shift+p (Windows)
2. Search for and then select "Continue: View Continue Server Logs"
3. Scroll to the bottom of `continue.log` and copy the last 100 lines or so

To get the VS Code console logs:

1. cmd+shift+p (MacOS) / ctrl+shift+p (Windows)
2. Search for and then select "Developer: Toggle Developer Tools"
3. Select Console
5. Read the console logs

If the problem is related to LLM prompting:

1. Hover the problematic response in the Continue UI
2. Click the "magnifying glass" icon
3. Copy the contents of the `continue_logs.txt` file that opens

**Screenshots**

**Additional context**

**Comment by sestinj** [comment] 2023-09-24 17:44
@cheuk-cheng When you type /edit does it show up in the dropdown like this?

<img width="497" alt="Screen Shot 2023-09-24 at 10 43 02 AM" src="https://github.com/continuedev/continue/assets/33237525/c33fda26-02b8-46d0-8cb3-a654161389a0">

And then once you press enter, does it display the loading box like this?
<img width="496" alt="Screen Shot 2023-09-24 at 10 44 37 AM" src="https://github.com/continuedev/continue/assets/33237525/35506516-fb70-4c80-8d5c-4f05ae624367">

**Comment by happy15** [comment] 2023-09-25 06:13
> @cheuk-cheng When you type /edit does it show up in the dropdown like this?
> 
> <img alt="Screen Shot 2023-09-24 at 10 43 02 AM" width="497" src="https://user-images.githubusercontent.com/33237525/270181964-c33fda26-02b8-46d0-8cb3-a654161389a0.png">
> And then once you press enter, does it display the loading box like this? <img alt="Screen Shot 2023-09-24 at 10 44 37 AM" width="496" src="https://user-images.githubusercontent.com/33237525/270182051-35506516-fb70-4c80-8d5c-4f05ae624367.png">

For me, both the file name and line numbers of the highlighted don't show, i.e. `settings.json (14-19)` in the example.

**Comment by cheuk-cheng** [comment] 2023-09-25 16:15
Thanks @sestinj.  After I upgraded continue extension in Visual Studio Code this morning, I can see the list of available options after I enter "/edit".  However, I am still seeing the following without any available log.

![screenshot 2023-09-25 at 09 11 28@2x](https://github.com/continuedev/continue/assets/72942052/c9c5f6aa-6176-43ec-81ac-12a78da7ca2a)

**Comment by brandonbiggs** [comment] 2023-09-26 17:52
I'm also having this issue. That was working last week for me, but isn't today when I try to use it.

**Comment by sestinj** [comment] 2023-09-26 19:17
@cheuk-cheng It is intentional that you have to use cmd+m to select new code - this makes it easier to select multiple ranges, and avoids situations where clicking around in files adds a ton of selected ranges to Continue. I realize this is a pretty fundamental change, and we're open to feedback if you feel strongly one way or the other

I do notice that there is no code currently selected here above the input box - if you give another try after 1. highlighting code, 2. using cmd+shift+m, 3. entering that same input, do you see the same error?

I also notice the `private/var/tmp` folder where the file is located. From my understanding, this is a folder with special privileges, which would cause the inability to select code or make an edit (access to those files might require 'sudo' access). In other folders does /edit seem to work?

**Comment by cheuk-cheng** [comment] 2023-09-26 20:36
Thanks @sestinj.  I cp test.py to ~/Downloads then highlighted the source lines shown below, pressed <cmd><shift>-m,  entered "/edit Optimize this Python code" and still saw the same thing (with no logs).
![screenshot 2023-09-26 at 13 34 42@2x](https://github.com/continuedev/continue/assets/72942052/e0c95815-a5e8-478a-ba4b-095e1202bc4e)

**Comment by sestinj** [comment] 2023-09-26 21:28
Ok, a couple of last questions to help me further investigate: when you highlight code, press cmd+m, and then type /edit, do you see a little paintbrush icon like this above the selected range?

<img width="430" alt="Screen Shot 2023-09-26 at 2 27 05 PM" src="https://github.com/continuedev/continue/assets/33237525/03ed497a-7723-4817-81cc-70dd642e2ea2">

And then more importantly if you open the console logs with cmd+shift+p, "Toggle Developer Tools", do you see any error messages related to Continue being unable to read a file? I think that the cause of the timeout should show up there

**Comment by cheuk-cheng** [comment] 2023-09-26 23:23
I did see the little paintbrush icon before I entered "/edit ...".  Please see the following screenshot.  However, I did not not any output after I toggle developer tools.
![screenshot 2023-09-26 at 16 20 57@2x](https://github.com/continuedev/continue/assets/72942052/e032daec-dc5a-41b7-893d-49509594189e)

**Comment by sestinj** [comment] 2023-09-27 19:32
Ok, the paintbrush is a good thing. What I'll do is improve the error logging here and then it should spit out exactly the error whenever it happens. I'll share an update soon

**Comment by sestinj** [comment] 2023-09-28 08:26
A few observations and a few updates in the latest version:
- It makes sense that this is only happening for /edit since normal chat doesn't use the sdk.ide.readFile websockets request
- Given that you are able to chat, I think it's probably not a fundamental problem with the websockets connection (the best way to confirm this would be to try to use the [@ terminal context provider](https://continue.dev/docs/reference/Context%20Providers/terminalcontextprovider), because it makes a similar request of the IDE
- So my instinct is that there is an error on the VS Code side when readFile is being called. The extension was already setup in previous version so that this would cause an error to be displayed like the below image, but if you weren't seeing this popup in the bottom right, then it's possible there was an error during error handling.
- I've added an additional console log (that would show up in developer tools console), and tried to avoid other sources of error so that the popup would definitely show up

<img width="456" alt="Screen Shot 2023-09-27 at 9 20 33 PM" src="https://github.com/continuedev/continue/assets/33237525/15f78b70-648e-434a-a72f-b5c452044186">

So my follow-up question (I wish I could instead be offering a fix, but alas) is:
Can you try this again on the newest version and then:
a) look for the popup
b) click the little icon in the thread next to "IDE Protocol _receive_json time out..." and check the details of the message there. This will show what the request data was and maybe shed light on the problem
c) If the popup doesn't show up, check the developer console logs again. I'd expect the error to show here

**Comment by cheuk-cheng** [comment] 2023-09-28 16:38
Thanks @sestinj.  I update all my installed extensions in Visual Studio Code and I only saw the following after I ran "/edit ...".  By the way, I am running Ollama v0.0.21 in maOS 13.
![screenshot 2023-09-28 at 09 35 04@2x](https://github.com/continuedev/continue/assets/72942052/8a866f8b-c165-4fbb-b689-5880de4e8666)

**Comment by sestinj** [comment] 2023-09-28 17:38
This is very odd...can you try using @ terminal? If it shows a similar timeout error, then it will be certain that there's a deeper bug

If the "Terminal" option doesn't already show when you type '@' you'll have to add it to config.py like

```pyrthon
from continuedev.src.continuedev.plugins.context_providers.terminal import TerminalContextProvider

config=ContinueConfig(
  ...
  context_providers=[TerminalContextProvider()]
)
```

**Comment by cheuk-cheng** [comment] 2023-09-28 17:52
I highlighted the same source lines, pressed <cmd>-shift-m, then entered "@terminal" and continue would explain the highlighted code fine.  When I entered "/edit ..." it failed with the same timeout error like before.

**Comment by sestinj** [comment] 2023-11-17 00:39
@cheuk-cheng Since this last comment we've made a number of fixes that have solved the timeout error. I'm going to close this issue on account of that, but if you're somehow still seeing the same thing feel free to re-open

**Closed by sestinj** 2023-11-17 00:39 UTC
