### ISSUE TITLE
Continue Plugin throws an UnsupportedOperationException while streaming response when context provided is 32.5 KB or more

### ISSUE THREAD

**Issue by swati-git** [continuedev/continue#770] opened 2024-01-22 04:18 UTC
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows
- Continue: 0.0.27
- IDE : IntelliJ IDEA 2023.2.4 (Community Edition)
- LLM : CodeLama
```

### Description

_Continue_ plugin when used with  _IntelliJ IDEA_ ,throws an UnsupportedOperationException when the _Context_ provided is of size 32.5 KB or more.
[continue_stacktrace.txt](https://github.com/continuedev/continue/files/14004543/continue_stacktrace.txt)

### To reproduce

Pre-Requisites:  
A LLM available to process your prompts.

1. Install the aforementioned Continue plugin version on IntelliJ.
2. Select an LLM of your choice, in this case CodeLlama-34b-Instruct-hf.
3. Provide a Context that is of size 32.5 KB or more. In this case a function written in Java 17.
4. Provide a prompt to refactor the function .

**Comment by sestinj** [comment] 2024-01-24 17:44
@swati-git Thanks for sharing the log. I've found the problem and have a fix, but we're working on a more roundabout method of solving this and many other long-awaited updates for JetBrains, so I'm going to ship them all at once this weekend. I will share a new version as soon as I have it ready, potentially even before it gets accepted to the store if you'd like early access

**Comment by sestinj** [comment] 2024-05-23 01:53
I'm just getting around to looking through older issues and found that this one has been solved, so I'm going to close the issue. Please let me know if for some reason the problem is still happening!

**Closed by sestinj** 2024-05-23 01:53 UTC
Labels: bug
