### ISSUE TITLE
 Crashing of vscode after installed the extension

### ISSUE THREAD

**Issue by GavinXue** [continuedev/continue#506] opened 2023-09-24 08:12 UTC
**Describe the bug**
When I installed the "continue" extension, Visual Studio Code crashed within one second. Subsequently, every time I attempted to start Visual Studio Code, it would crash repeatedly until I uninstalled the "continue" extension.

I have attempted to download the server binary from the [continue.dev](https://continue.dev/docs/walkthroughs/manually-run-continue#download-the-server-binary) website and run the server manually. However, the success rate is inconsistent; sometimes it works, and sometimes it does not.

Are there others who have experienced similar issues?

**Environment**

- Operating System: MacOS 13.6
- Python Version: 3.9.16
- vscode version: 1.81.1
- Continue Version: 0.0.396

**Logs**
because can not open vscode when installed continue, can not get logs

**Screenshots**
![](https://github.com/GavinXue/public-img/blob/main/issues/continue_crash.gif?raw=true)

**Comment by sestinj** [comment] 2023-09-24 08:33
Is this the first time you've installed Continue, or is it unique to this version? While I'm not yet sure what would cause this problem and haven't seen it before, I have a couple of naive things to try if you're up for it:
- this might be related to a bug that was fixed in the newest version (0.0.397)
- I'm in a similar environment on Mac, except using VS Code version 1.82.2—maybe upgrading is worth a check, even though it's very close?

What's striking is that this happens _instantly_, which means there wasn't a lot of time for code to run, so it might be something at the configuration level

**Comment by GavinXue** [comment] 2023-09-24 09:14
> Is this the first time you've installed Continue, or is it unique to this version? While I'm not yet sure what would cause this problem and haven't seen it before, I have a couple of naive things to try if you're up for it:
> 
> * this might be related to a bug that was fixed in the newest version (0.0.397)
> * I'm in a similar environment on Mac, except using VS Code version 1.82.2—maybe upgrading is worth a check, even though it's very close?
> 
> What's striking is that this happens _instantly_, which means there wasn't a lot of time for code to run, so it might be something at the configuration level

I first encountered this problem around a month ago, when my 'Continue' extension was probably on version 0.0.383. I'm really fond of this extension, so I've been waiting for a new version to help fix the issue. I've attempted to solve this by both upgrading and downgrading the 'Continue' version as well as upgrading my Visual Studio Code (VSCode) version. Unfortunately, none of these actions have worked.

Upon installing 'Continue,' I found that I was no longer able to open VSCode. This seems to occur because the startup of 'Continue' causes VSCode to quit. I suspect there may be some conflict during the run of 'Continue,' potentially at the configuration level as you suggested. However, I've been unable to pinpoint the specific issue. If you require my VSCode configuration file to assist you, please let me know which details or components I should provide.

**Comment by sestinj** [comment] 2023-09-24 17:39
Well I'm really sorry this has been happening so long :/ There are two experiments that I think would provide useful information:
1. In VS Code settings (probably use JSON since the UI won't show unless Continue is installed), add `"continue.manuallyRunningServer": true`, and then try re-installing Continue. This will stop Continue from downloading the server, and tell us whether that was the problem. Since you said that manual download sometimes works, I think this might be important
2. Right before you download Continue, use "cmd+shift+p" and then select "Toggle Developer Tools" and open the console. Continue might output some logs that will tell us how far it gets before crashing. Might have to take a video to catch these before they disappear immediately

**Comment by GavinXue** [comment] 2023-09-25 01:08
@sestinj I have tried. here is what happened:

1. I set `"continue.manuallyRunningServer"=true` in the config, then I reinstalled 'Continue'. VSCode doesn't close out anymore. Here's how the logs look like after that:
![continue_manual_start_true](https://github.com/GavinXue/public-img/blob/main/issues/continue_manual_start_true.png?raw=true)

2. I try to open  console and record the window before vscode crashed, just get a video here: [before_crash_video](https://github.com/GavinXue/public-img/blob/main/issues/before_continue_crash_20230925.mp4), and next img is the last frame from vedio before vscode quit. (I have try 3 times, just one time capture the logs, sometimes the logs will not show before quit)
![last_frame](https://github.com/GavinXue/public-img/blob/main/issues/before_continue_crashed.png?raw=true)

**Comment by sestinj** [comment] 2023-09-25 01:16
Thanks for this! The first result means that there should be a good temporary solution for you. If you keep the box checked in settings, then setup a server like [here](https://continue.dev/docs/walkthroughs/manually-run-continue#recommended-use-the-continuedev-pypi-package), then I would expect Continue to work. (if not then there will probably be a lot of information that comes alongside)

The second result helps me pin down the problem. Pretty clear that the problem is either in trying to kill an old version of the server or downloading a new one.

**Comment by GavinXue** [comment] 2023-09-25 01:28
Thanks for your advice. I found that `download server binary` in [manual server doc](https://continue.dev/docs/walkthroughs/manually-run-continue#recommended-use-the-continuedev-pypi-package) has 404 error.

Add some more information, I have tried to close vpn/ firewall/ adguard and so on, it doesn't work. I'm not sure whether my being in China is causing this issue. Could you provide me with the URL for the 'Continue' server? I'd like to add it to my VPN and give it a try.

If you need more info for this issue, plz let me know.

**Comment by sestinj** [comment] 2023-09-25 01:41
I've heard of the 404 from someone in Europe as well, so it doesn't sound China-specific, but definitely geography-related. I would guess it's probably still possible to download the PyPI package

There are two sets of URLs (one for backup):
https://s3.continue.dev/mac/run (and can replace `mac` with `apple-silicon`, `windows`, or `linux`. If using `windows`, the last part also needs to be changed to `run.exe`)
and the backup is https://continue-server-binaries.s3.us-west-1.amazonaws.com/mac/run, same paths as above

**Comment by GavinXue** [comment] 2023-09-25 02:12
> I've heard of the 404 from someone in Europe as well, so it doesn't sound China-specific, but definitely geography-related. I would guess it's probably still possible to download the PyPI package
> 
> There are two sets of URLs (one for backup): https://s3.continue.dev/mac/run (and can replace `mac` with `apple-silicon`, `windows`, or `linux`. If using `windows`, the last part also needs to be changed to `run.exe`) and the backup is https://continue-server-binaries.s3.us-west-1.amazonaws.com/mac/run, same paths as above

Thanks, the backup download link is working for me.

**Comment by GavinXue** [comment] 2023-09-25 03:26
😭 Failed again when using manual server. The logs display a recurring download of MeiliSearch,  and Vscode continue extension always show `Continue Server Starting`.
some info:
Python 3.9.16
python env manage tool: mambaforge
macOS: Apple M1 Max Ventura 13.6 (22G120)

Is there any setting I missed. I have followed the [Troubleshooting](https://continue.dev/docs/troubleshooting) suggestions in the documentation.

- Using `python m continuedev`
![using python](https://github.com/GavinXue/public-img/blob/main/issues/continue/repeat_download_melisearch_using_python-m-continuedev.jpg?raw=true)

- Using `./run` binary file
![using binary](https://github.com/GavinXue/public-img/blob/main/issues/continue/repeat_to_download_melisearch_using_binaryfile.jpg?raw=true)

**Comment by sestinj** [comment] 2023-09-25 04:18
Sorry this has been such a pain...you aren't doing anything wrong. It looks like we're getting closer though. My guess is that this would be the last hurdle, because it's the last thing that needs to be downloaded. If either you [manually downloaded and started meilisearch](https://www.meilisearch.com/docs/learn/getting_started/installation), or I add a flag to not attempt the download this would no longer be a problem

**Comment by GavinXue** [comment] 2023-09-25 05:29
Thanks for your reply. I have download meilisearch using Homebrew, but it doesn not work. I guess maybe I should be put it in right place. so I check in the code. I put it in the folder `~/.continue/server`, Then the server works. here is logs

```
Gavin-MacBook :: ~/VScode/continue » python -m continuedev
[2023-09-25 13:16:05,552] [DEBUG] Testing logs
INFO:     Started server process [80331]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:65432 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 58068) - "WebSocket /ide/ws" [accepted]
[2023-09-25 13:16:09,621] [DEBUG] Accepted websocket connection from Address(host='127.0.0.1', port=58068)
INFO:     connection open
INFO:     ('127.0.0.1', 58069) - "WebSocket /ide/ws" [accepted]
[2023-09-25 13:16:09,670] [DEBUG] Accepted websocket connection from Address(host='127.0.0.1', port=58069)
INFO:     connection open
INFO:     ('127.0.0.1', 58070) - "WebSocket /ide/ws" [accepted]
[2023-09-25 13:16:09,671] [DEBUG] Accepted websocket connection from Address(host='127.0.0.1', port=58070)
[2023-09-25 13:16:09,699] [DEBUG] Received message while initializing workspaceDirectory
[2023-09-25 13:16:09,699] [DEBUG] Received message while initializing uniqueId
INFO:     connection open
[2023-09-25 13:16:09,727] [DEBUG] Received message while initializing workspaceDirectory
[2023-09-25 13:16:09,728] [DEBUG] Received message while initializing uniqueId
[2023-09-25 13:16:09,728] [DEBUG] Received message while initializing workspaceDirectory
[2023-09-25 13:16:09,728] [DEBUG] Received message while initializing uniqueId
[2023-09-25 13:16:09,734] [DEBUG] Starting MeiliSearch...
[2023-09-25 13:16:09,741] [DEBUG] Starting MeiliSearch...
[2023-09-25 13:16:09,745] [DEBUG] Starting MeiliSearch...
INFO:     ('127.0.0.1', 58146) - "WebSocket /ide/ws" [accepted]
[2023-09-25 13:16:46,065] [DEBUG] Accepted websocket connection from Address(host='127.0.0.1', port=58146)
```

❗️However when I start Continue in vscode, I encountered an error. Next is logs, Is there anything I can do to fix it?

```
2023-09-25 13:16:46,065] [DEBUG] Accepted websocket connection from Address(host='127.0.0.1', port=58146)
INFO:     connection open
[2023-09-25 13:16:46,109] [DEBUG] Received message while initializing workspaceDirectory
[2023-09-25 13:16:46,113] [DEBUG] Received message while initializing uniqueId
[2023-09-25 13:16:47,063] [DEBUG] New session: None
Exception in callback create_async_task.<locals>.callback(<Task finishe...e' and 'tb'")>) at /Users/GavinXue/mambaforge/lib/python3.9/site-packages/continuedev/libs/util/create_async_task.py:19
handle: <Handle create_async_task.<locals>.callback(<Task finishe...e' and 'tb'")>) at /Users/GavinXue/mambaforge/lib/python3.9/site-packages/continuedev/libs/util/create_async_task.py:19>
Traceback (most recent call last):
  File "/Users/GavinXue/mambaforge/lib/python3.9/site-packages/continuedev/core/sdk.py", line 75, in create
    sdk.config = config or sdk._load_config_dot_py()
  File "/Users/GavinXue/mambaforge/lib/python3.9/site-packages/continuedev/core/sdk.py", line 242, in _load_config_dot_py
    config = ContinueConfig.from_filepath(path)
  File "/Users/GavinXue/mambaforge/lib/python3.9/site-packages/continuedev/core/config.py", line 112, in from_filepath
    spec.loader.exec_module(config)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/GavinXue/.continue/config.py", line 7, in <module>
    from continuedev.src.continuedev.core.models import Models
ModuleNotFoundError: No module named 'continuedev.src'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GavinXue/mambaforge/lib/python3.9/site-packages/continuedev/server/session_manager.py", line 92, in new_session
    await autopilot.start(full_state=full_state, config=config)
  File "/Users/GavinXue/mambaforge/lib/python3.9/site-packages/continuedev/core/autopilot.py", line 112, in start
    self.continue_sdk = await ContinueSDK.create(self, config=config)
  File "/Users/GavinXue/mambaforge/lib/python3.9/site-packages/continuedev/core/sdk.py", line 77, in create
    logger.error(f"Failed to load config.py: {traceback.format_exception(e)}")
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GavinXue/mambaforge/lib/python3.9/site-packages/continuedev/libs/util/create_async_task.py", line 21, in callback
    future.result()
  File "/Users/GavinXue/mambaforge/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/GavinXue/mambaforge/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/GavinXue/mambaforge/lib/python3.9/site-packages/continuedev/server/ide.py", line 223, in handle_json
    await self.getSessionId()
  File "/Users/GavinXue/mambaforge/lib/python3.9/site-packages/continuedev/server/ide.py", line 310, in getSessionId
    new_session = await asyncio.wait_for(
  File "/Users/GavinXue/mambaforge/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/Users/GavinXue/mambaforge/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/Users/GavinXue/mambaforge/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/Users/GavinXue/mambaforge/lib/python3.9/site-packages/continuedev/server/session_manager.py", line 94, in new_session
    await ide.on_error(e)
  File "/Users/GavinXue/mambaforge/lib/python3.9/site-packages/continuedev/server/ide.py", line 345, in on_error
    err_msg = "\n".join(traceback.format_exception(e))
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
```

**Comment by sestinj** [comment] 2023-09-25 06:48
Glad it's up and running!! This is a known error: there are differences in how the import works when manually running the server. Before I get around to fixing this, you can open `~/.continue/config.py` and change all `continuedev.src.continuedev...` to just `continuedev...`. This will solve the problem here

**Comment by GavinXue** [comment] 2023-09-25 10:52
Thank you for the detailed guide. It's now working as expected. I've found that it doesn't work locally, and it's possible that the connection between the local and remote server is being blocked by China's Great Firewall.

**Comment by sestinj** [comment] 2023-10-10 21:25
@GavinXue I wanted to update you that we are now shipping the VS Code extension with the binary built-in, so this download after-the-fact no longer has to happen (you shouldn't have to run it manually).

I'm going to close this issue because I think additional problems would be best handled in a new thread, but please don't hesitate to open one if something else comes up.

Cheers,
Nate

**Closed by sestinj** 2023-10-10 21:25 UTC
