### ISSUE TITLE
Error getting context items from folder

### ISSUE THREAD

**Issue by HakaishinShwet** [continuedev/continue#983] opened 2024-03-18 14:27 UTC
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Linux
- IDE:vscode
```

### Description

trying to feed folder and get answer for some files but getting this error 

### Log output

```Shell
Error getting context items from folder: Error: `local_files_only=true` or `env.allowRemoteModels=false` and file was not found locally at "/config/extensions/continue.continue-0.8.16-linux-x64/models/all-MiniLM-L6-v2/tokenizer.json".
```

**Comment by alexsoyes** [comment] 2024-03-19 14:39
Same issue here when trying to index some documentation and then query it from chat:

```text
Error getting context items from docs: Error: lance error: LanceError(IO): Schema error: No field named baseurl. Valid fields are title, "baseUrl", content, path, "startLine", "endLine", vector., /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-0.10.4/src/io/exec/planner.rs:659:20
```

**Comment by sestinj** [comment] 2024-03-22 01:12
@alexsoyes I just solved this [here](https://github.com/continuedev/continue/commit/15fd7ae3311c48abbb162383b584c3afd3ca6b42). Either it's in the current pre-release or will be in the next one

**Comment by thebetauser** [comment] 2024-05-05 14:08
@sestinj will this fix be pushed to jetbrains plugin? I'm on 0.0.46 and I'm experiencing this issue as well

**Comment by bradleymize** [comment] 2024-06-07 22:40
* OS: Windows
* IDE: Jetbrain IntelliJ IDEA 2024.1
* Continue Plugin: 0.0.50

Similar issue on Windows w/ the Jetbrains plugin, this appears in the logs on start up:

```
[info] Starting Continue core...
[2024-06-07T22:35:39] [info] Starting Continue core... 
[2024-06-07T22:35:40] Error updating the vectordb::all-MiniLM-L6-v2 index: Error: `local_files_only=true` or `env.allowRemoteModels=false` and file was not found locally at "C:\snapshot\continue-deploy\binary\models/all-MiniLM-L6-v2/tokenizer.json". 
```

The `tokenizer.json` file does not exist locally (nor does `C:\snapshot` for that matter).

**Comment by Cheizr** [comment] 2024-06-13 11:35
Fresh installation, when using the @folder context:

Error getting context items from folder: Error: Schema
Error. No vector column found to create index
Source: Continue - Codestral, GPT-40, and more

**Comment by Devil-Mix** [comment] 2024-06-16 14:00
I'm getting this error message. 

`Error getting context items from folder: SyntaxError: Unexpected end of JSON input`

I'm using Linux on a remote VSCode server.

**Comment by sestinj** [comment] 2024-06-17 01:54
@womd @bradleymize we don't currently support the transformers.js embeddings provider on JetBrains, which is why you're seeing this error. In newer versions we'll have a more clear warning, but for now the solution is to use "ollama" or another embeddings provider: https://docs.continue.dev/walkthroughs/codebase-embeddings#embeddings-providers

**Comment by sestinj** [comment] 2024-06-17 01:55
@Devil-Mix it looks like your problem is entirely different. Can you share what your config.json looks like?

**Comment by bradleymize** [comment] 2024-06-17 02:14
> @womd @bradleymize we don't currently support the transformers.js embeddings provider on JetBrains, which is why you're seeing this error. In newer versions we'll have a more clear warning, but for now the solution is to use "ollama" or another embeddings provider: https://docs.continue.dev/walkthroughs/codebase-embeddings#embeddings-providers

@sestinj Thanks for the clarification. Confirmed I could use the code in [Writing a custom EmbeddingsProvider](https://docs.continue.dev/walkthroughs/codebase-embeddings#embeddings-providers) and updating the url to LM Studio's `http://localhost:1234/v1/embeddings` and indexing was successful after restarting IntelliJ.

For anyone else with this issue, I updated `config.ts` as documented, and removed the configuration in `config.json` for the `embeddingsProvider`.

**Comment by sestinj** [comment] 2024-06-17 07:04
Very nice! One other way to approach this would be using the "openai" embeddingsProvider with an apiBase pointing to LMStudio, as it is OpenAI-compatible

**Closed** 2024-06-17 07:04 UTC
Labels: bug

**Comment by Devil-Mix** [comment] 2024-06-20 20:09
> @Devil-Mix it looks like your problem is entirely different. Can you share what your config.json looks like?

Thx. I think it was something I did when adding workspace. It's working fine now.

**Comment by Devil-Mix** [comment] 2024-06-20 20:11
@sestinj 
> @Devil-Mix it looks like your problem is entirely different. Can you share what your config.json looks like?
Thx. I think it was something I did when adding workspace. It's working fine now.

**Comment by Devil-Mix** [comment] 2024-06-20 20:13
@sestinj 

> @Devil-Mix it looks like your problem is entirely different. Can you share what your config.json looks like?

Thx. It's working fine now. I think it was something to do with when adding workspace.

**Comment by Cheizr** [comment] 2024-06-21 10:22
It's working for me now!
