### ISSUE TITLE
continueignore doesn't override gitignore

### ISSUE THREAD

**Issue by richardbowman** [continuedev/continue#2889] opened 2024-11-12 18:54 UTC
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 11 / WSL2 (Ubuntu 22.04.3 LTS (GNU/Linux 5.15.153.1-microsoft-standard-WSL2 x86_64)
- Continue version: Latest pre-release (11/12/2024)
- IDE version:
- Model:
- config.json:
```

### Description

I've got a directory of generated assets that are set to .gitignore:

```
schemas
```

That I want Continue's context to use. I've created a .continueignore file with:

```
!schemas
```

But this seems to have no effect.

**Comment by sestinj** [comment] 2024-11-14 16:54
Hm yeah this is an interesting use case I hadn't thought of. I think that given our proclivity to leave the indexing logic stable as possible I might not immediately try and tackle this, but if you were interested in attempting a PR I'd be open to reviewing. It should be reasonably straightforward to verify the behavior with our tests

Out of curiosity, are these SQL database schemas?

**Comment by richardbowman** [comment] 2024-11-14 17:49
In my case, they are GraphQL schemas. I'll see if I can get a version
working. Any off the cuff notes on code areas to point me at?

**Comment by sestinj** [comment] 2024-11-14 18:01
Yeah it's the walkDir function that is relevant: https://github.com/continuedev/continue/blob/39a8e158cf737910cd4950d947bb5e439ec7de6d/core/indexing/walkDir.ts#L17

Most importantly start with a few new test cases in walkDir.test.ts, that should make life a lot easier.

I also want to call out that there was [a previous attempt at this](https://github.com/continuedev/continue/pull/2802), and I'd closed it because there was quite a lot of diff and it wasn't tested super rigorously. My benchmark for this is very high confidence from both tests and minimal changes that no critical behavior will drift.

**Comment by RomneyDa** [comment] 2024-11-19 18:49
Duplicate of https://github.com/continuedev/continue/issues/2739

**Comment by sestinj** [comment] 2024-11-20 07:04
closing bc of duplication

**Closed by sestinj** 2024-11-20 07:04 UTC
Labels: area:indexing, kind:bug, priority:medium
