### ISSUE TITLE
Server disconnected 

### ISSUE THREAD

**Issue by Gsuz** [continuedev/continue#434] opened 2023-08-30 21:50 UTC
**Describe the bug**
Getting server disconnected around 70-80% of the times I try to use a prompt. 

**To Reproduce**
1. Use prompt
2. See error

**Expected behavior**
It should not disconnect

**Screenshots**

**Environment**
- Operating System: [MacOS with M1 MAX 64 GB
- Using Ollama
- Continue Version: [0.0.352]

**Console logs**
```
Traceback (most recent call last):

  File "continuedev/src/continuedev/core/autopilot.py", line 368, in _run_singular_step
    observation = await step(self.continue_sdk)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "continuedev/src/continuedev/core/main.py", line 359, in __call__
    return await self.run(sdk)
           ^^^^^^^^^^^^^^^^^^^

  File "continuedev/src/continuedev/plugins/steps/chat.py", line 85, in run
    async for chunk in generator:

  File "continuedev/src/continuedev/libs/llm/ollama.py", line 158, in stream_chat
    async with self._client_session.post(

  File "aiohttp/client.py", line 1141, in __aenter__

  File "aiohttp/client.py", line 560, in _request

  File "aiohttp/client_reqrep.py", line 899, in start

  File "aiohttp/streams.py", line 616, in read

  File "asyncio/futures.py", line 287, in __await__

  File "asyncio/tasks.py", line 339, in __wakeup

  File "asyncio/futures.py", line 203, in result

aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

**Additional context**
Nothing to add

**Comment by sestinj** [comment] 2023-08-30 21:52
Could you share the contents of the Ollama class in your config.py?

**Comment by Gsuz** [comment] 2023-08-30 21:53
from continuedev.src.continuedev.core.models import Models
from continuedev.src.continuedev.core.config import CustomCommand, SlashCommand, ContinueConfig
from continuedev.src.continuedev.plugins.context_providers.github import GitHubIssuesContextProvider
from continuedev.src.continuedev.libs.llm.maybe_proxy_openai import MaybeProxyOpenAI

from continuedev.src.continuedev.plugins.steps.open_config import OpenConfigStep
from continuedev.src.continuedev.plugins.steps.clear_history import ClearHistoryStep
from continuedev.src.continuedev.plugins.steps.feedback import FeedbackStep
from continuedev.src.continuedev.plugins.steps.comment_code import CommentCodeStep
from continuedev.src.continuedev.plugins.steps.share_session import ShareSessionStep
from continuedev.src.continuedev.plugins.steps.main import EditHighlightedCodeStep
from continuedev.src.continuedev.plugins.context_providers.search import SearchContextProvider
from continuedev.src.continuedev.plugins.context_providers.diff import DiffContextProvider
from continuedev.src.continuedev.plugins.context_providers.url import URLContextProvider
from continuedev.src.continuedev.plugins.context_providers.terminal import TerminalContextProvider
from continuedev.src.continuedev.libs.llm.ollama import Ollama

config = ContinueConfig(
    allow_anonymous_telemetry=False,
    models=Models(
        default=Ollama(model="wizardcoder:34b-python")
    ),
    system_message="",
    temperature=0.5,
    custom_commands=[
        CustomCommand(
            name="test",
            description="Write unit tests for the higlighted code",
            prompt="Write a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
        )
    ],
    slash_commands=[
        SlashCommand(
            name="edit",
            description="Edit code in the current file or the highlighted code",
            step=EditHighlightedCodeStep,
        ),
        SlashCommand(
            name="config",
            description="Customize Continue - slash commands, LLMs, system message, etc.",
            step=OpenConfigStep,
        ),
        SlashCommand(
            name="comment",
            description="Write comments for the current file or highlighted code",
            step=CommentCodeStep,
        ),
        SlashCommand(
            name="feedback",
            description="Send feedback to improve Continue",
            step=FeedbackStep,
        ),
        SlashCommand(
            name="clear",
            description="Clear step history",
            step=ClearHistoryStep,
        ),
        SlashCommand(
            name="share",
            description="Download and share the session transcript",
            step=ShareSessionStep,
        )
    ],
    context_providers=[
        # GitHubIssuesContextProvider(
        #     repo_name="<your github username or organization>/<your repo name>",
        #     auth_token="<your github auth token>"
        # ),
        SearchContextProvider(),
        DiffContextProvider(),
        URLContextProvider(
            preset_urls = [
                # Add any common urls you reference here so they appear in autocomplete
            ]
        ),
        TerminalContextProvider(),
    ],
)

**Comment by sestinj** [comment] 2023-08-30 22:01
Thanks. I'll try this exact setup on my own machine to see if I can reproduce. The first thing I would check is that you've pulled the model you are using, but I'm quite confident you already know to do this. I'll give an update soon

**Comment by Gsuz** [comment] 2023-08-30 22:09
ollama list
NAME                  	ID          	SIZE  	MODIFIED          
codellama:latest      	36893bf9bc7f	3.8 GB	4 hours ago      	
wizardcoder:34b-python	1064f08e84a4	19 GB 	About an hour ago

**Comment by sestinj** [comment] 2023-08-30 22:19
From one of the ollama founders: "We've seen some issues with large prompts with the 34B models – looking into this - sorry!!"

I'm wondering whether the first message you send (when chat history is empty, or right after loading ollama) might work, while later messages don't because of the built up context. Unfortunately I don't have the hardware to test this on my own with a 34b

**Comment by Gsuz** [comment] 2023-08-30 22:49
> From one of the ollama founders, it sounds like they are having issues with 34b models with long context inputs.

This is probably true. I see this aswell. Yeah I'll try a smaller model. Any special you recommend?

**Comment by sestinj** [comment] 2023-08-30 23:11
I've been seeing really great results from codellama:13b-instruct, with the instruct part being crucial. Even 7b is decent

**Comment by sestinj** [comment] 2023-09-01 22:31
I'm going to close this issue since it seems mostly resolved, but you're feel free to reopen if something is still wrong. Let me know if you have any more questions about models to use!

**Closed by sestinj** 2023-09-01 22:31 UTC
