### ISSUE TITLE
Compatibility: LLama Message Order

### ISSUE THREAD

**Issue by adrianliechti** [continuedev/continue#488] opened 2023-09-18 21:55 UTC
LLama only supports messages in this order: 'system', 'user' and 'assistant' roles, starting with 'system', then 'user' and alternating (u/a/u/a/u...)

continue.dev sends two user role messages in a row (one with the text, one with the code snippet).
could you consider to merge these client-side? or is there already an option to merge them?

**Comment by sestinj** [comment] 2023-09-18 21:56
There's no option as of now, but I've been thinking about finally merging into a single user prompt.

Curious: does this seem to be the cause of low-quality responses?

**Comment by adrianliechti** [comment] 2023-09-18 22:44
as far as i understand the fine-tuning of a model is configured for a specific flow. I could imagine that ignoring that could end up in suboptimal results.


in the case of llama, they have a check in their implementation:
https://github.com/facebookresearch/codellama/blob/d2b38acd3a9c55051de1f21d9132f61de7d1a630/llama/generation.py#L309

**Comment by sestinj** [comment] 2023-10-10 21:38
@adrianliechti I've played around with this formatting and found that there doesn't seem to be any downgrade in capabilities from using the different ordering. But I wanted to check with you as well before closing this issue - have you noticed any poor responses coming from Continue?

**Comment by adrianliechti** [comment] 2023-10-13 15:36
feel free to close this!! and thanks a ton

I also implemented a "flattering" of the order in my proxy by combining the role's messages:
https://github.com/adrianliechti/llama/blob/main/llama-openai/provider/llama/llama.go#L271

**Comment by sestinj** [comment] 2023-10-13 17:47
cool! Did you notice a quality difference after doing this?

**Comment by sestinj** [comment] 2023-10-13 22:11
ok going to close this because (really funny timing) someone just [brought up](https://discord.com/channels/1108621136150929458/1162505725281583244) that pplx-api enforces the chat message ordering! So made the change inspired by your flattening function, and going to keep it in pre-release for a bit

**Closed by sestinj** 2023-10-13 22:11 UTC
