### ISSUE TITLE
All UI controls in the tool window are disabled

### ISSUE THREAD

**Issue by danny-su** [continuedev/continue#537] opened 2023-10-07 14:14 UTC
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS 14
- Continue: IntelliJ Plugin
```

### Description

All UI controls in the tool window are disabled, can't type anything or click the Continue button.
BTW, I installed material theme ui and gerry themes pro, and  Continue works well in vs code.
<img width="346" alt="image" src="https://github.com/continuedev/continue/assets/12178855/cde01a92-e5ae-4ae2-b1c8-e3fbcbdd4c43">

**Comment by sestinj** [comment] 2023-10-07 20:04
@danny-su Sorry about this, but thanks for giving early feedback on the alpha version! We're waiting on JetBrains to accept our latest version, but if you'd like you can install it from disk using this .zip file here. This will fix the freezing problem and also match your color scheme.

To install from disk, open Intellij settings (command+comma), go to "Plugins" in the sidebar, click the gear icon at the top, and select "Install from Disk"

[continue-intellij-extension-0.0.7.zip](https://github.com/continuedev/continue/files/12838813/continue-intellij-extension-0.0.7.zip)

**Comment by danny-su** [comment] 2023-10-08 02:54
@sestinj I installed the version 0.0.7, but this issue wasn't fixed.
<img width="855" alt="image" src="https://github.com/continuedev/continue/assets/12178855/7bcf7ffa-5de7-4ea4-9c17-d07f75b15ddb">

**Comment by sestinj** [comment] 2023-10-08 03:35
Interesting, sorry to see that - I'll be sure that it's fixed before the official version is released to the store this week, and I'll share another zip before that if you are interested

**Comment by iamjackg** [comment] 2023-10-13 13:36
This occasionally happens to me too with version 0.0.8, but I couldn't figure out what triggers it. Sometimes when I reopen the Continue pane it has that "Nothing to show" label in the middle and the UI doesn't respond. I can still "use" the plugin with keyboard shortcuts, but I can't click on anything.

**Comment by sestinj** [comment] 2023-10-13 18:02
@iamjackg good to know this isn't isolated. I've seen it on my machine as well, so I'm currently working through this and should hopefully have something new on the store by beginning of next week

In the times that it hasn't been frozen, have there been any other imperfections you've noticed? Working toward releasing this officially, so all feedback will help make it better!

**Comment by iamjackg** [comment] 2023-10-16 14:52
Yeah, a couple things I noticed:
* the window that shows an incremental diff as it's being returned by the LLM changes size and flickers with every update.
* in the same window, the keyboard shortcuts at the bottom have Mac key labels (I'm on Linux)

Haven't tried v0.11 yet, so I don't know if those were already fixed :)

**Comment by iamjackg** [comment] 2023-10-16 14:58
Usability: for some reason, ctrl+backspace erases the entire input textbox instead of just the previous word.

**Comment by iamjackg** [comment] 2023-10-16 18:42
I just realized I can't copy-paste things in the textbox either. Right clicking does nothing, and ctrl+c and ctrl+v do nothing. This is on 0.11

**Comment by sestinj** [comment] 2023-10-16 19:08
@iamjackg
- Should be ^ (ctrl) instead of cmd for Linux, right?
- Is inability to ctrl+c only in the text box, or everywhere?

And should be quick fixes for the flickering and ctrl+backspace (JetBrains was overriding it so I had to implement the behavior manually, forgot that behavior is different on Windows/Linux vs. Mac). I'll have this in 0.0.12

**Comment by iamjackg** [comment] 2023-10-16 19:16
`^` is a common representation, yes, but if you want to keep with the JetBrains UX/UI you should probably use `Ctrl`.

> Is inability to ctrl+c only in the text box, or everywhere?
Seems to be just in the textbox. I can select and ctrl+c the Tutorial text for example.

![image](https://github.com/continuedev/continue/assets/19474350/d2a561b4-46ca-45a3-858d-c144d316fc29)

In general, the keyboard behaviour in the textbox is pretty weird :thinking: <kbd>Ctrl</kbd>+<kbd>Left</kbd> and <kbd>Ctrl</kbd>+<kbd>Right</kbd> are supposed to move left and right word-by-word, instead they go to the start and end of the text. If I press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Left</kbd> to select the previous word, it will select the whole text. At that point, if I press <kbd>Shift</kbd>+<kbd>Left</kbd> or <kbd>Shift</kbd>+<kbd>Right</kbd> to modify the selection, it will move the end of the selection that the caret was originally at. I have no idea if it's because you're implementing a custom textbox component for the webview, but this is all very confusing :laughing:

**Comment by sestinj** [comment] 2023-10-17 03:30
@iamjackg thanks, makes sense.

All of that weird behavior is the Mac default lol, all simulated manually by us : ) I'll change this to reflect the OS

**Comment by timdahlmanns** [comment] 2023-10-17 13:06
> I just realized I can't copy-paste things in the textbox either. Right clicking does nothing, and ctrl+c and ctrl+v do nothing. This is on 0.11

+1

Had the non responsive UI besides shortcuts as well, but not in 0.0.11 so far

**Comment by iamjackg** [comment] 2023-10-18 15:37
Lots of improvements in 0.13! No more diff flickering :)

One more usability issue: when the diff becomes longer than what can be shown on the screen, I can't scroll to keep up with the changes, because every new token coming in resets the scroll position to the top of the diff.

**Comment by sestinj** [comment] 2023-10-18 19:25
@timdahlmanns I believe that ctrl+c has been been solved in 0.0.13, but ctrl+v might not be working yet

@iamjackg inability to scroll is a good point, I'll take a look at this for the next release

Does the stop button eventually return to saying Continue, or is it stuck indefinitely?

**Comment by timdahlmanns** [comment] 2023-10-19 06:31
> @timdahlmanns I believe that ctrl+c has been been solved in 0.0.13, but ctrl+v might not be working yet

For me (on Linux) neither `ctrl+c` nor `ctrl+shift+c` works but `ctrl+shift+v` for insert works, `ctrl+v` does not.

**Comment by iamjackg** [comment] 2023-10-19 13:35
> Does the stop button eventually return to saying Continue, or is it stuck indefinitely?

It does go back to saying Continue, it's just the first context item that stays stuck.

**Comment by sestinj** [comment] 2023-10-24 01:10
@timdahlmanns I've been testing a few things but don't have a linux machine to validate my guesses.

The few things I'm wondering:
- We are mapping the keyboard shortcut incorrectly (does alt/option/any other + v work to paste?)
- Perhaps there is a separate clipboard in the web view on linux. Are you able to copy text from within the webview and paste it elsewhere inside of the webview?
- **And the most important question**: If you go to the settings page (gear icon in the bottom right of the Continue web view) are you able to copy/paste in the system prompt textarea? This would tell me immediately whether it's a bug specific to the input box

**Comment by iamjackg** [comment] 2023-11-07 22:08
I really don't know what's going on, but I cannot get Continue to use my OpenAI token when editing code. It seems to always revert back to the free trial.

```
[2023-11-07 17:03:22,753] [DEBUG] ------ Begin Logs ------
[2023-11-07 17:03:23,022] [DEBUG] Loaded Continue config file from /home/jack.gaino/.continue/config.py
[2023-11-07 17:03:23,055] [DEBUG] Starting context manager
[2023-11-07 17:03:23,056] [WARNING] Failed to load saved_context_groups.json: Expecting value: line 1 column 1 (char 0). Reverting to empty list.
[2023-11-07 17:03:23,093] [DEBUG] Sending session id: 7beec213-5f64-457a-978b-c4d42c41e19c
[2023-11-07 17:03:23,098] [DEBUG] Loading Meilisearch index...
[2023-11-07 17:03:23,134] [DEBUG] Error loading meilisearch index: 'list' object has no attribute 'items'
[2023-11-07 17:03:23,136] [WARNING] Failed to kill process on port 7700 (access denied)
[2023-11-07 17:03:23,136] [DEBUG] Using MeiliSearch at URL: http://localhost:7700
[2023-11-07 17:03:23,182] [DEBUG] Loaded 0 documents into meilisearch in 0.0034575462341308594 seconds for context provider code
[2023-11-07 17:03:23,188] [DEBUG] Loaded 1 documents into meilisearch in 0.00953054428100586 seconds for context provider diff
[2023-11-07 17:03:23,193] [DEBUG] Loaded 1 documents into meilisearch in 0.014801263809204102 seconds for context provider terminal
[2023-11-07 17:03:23,194] [DEBUG] Loaded 1 documents into meilisearch in 0.015567779541015625 seconds for context provider url
[2023-11-07 17:03:23,617] [DEBUG] Received websocket connection at url: ws://localhost:65432/gui/ws?session_id=7beec213-5f64-457a-978b-c4d42c41e19c
[2023-11-07 17:03:23,617] [DEBUG] Session started
[2023-11-07 17:03:23,617] [DEBUG] Registered websocket for session 7beec213-5f64-457a-978b-c4d42c41e19c
[2023-11-07 17:03:23,733] [DEBUG] Received websocket connection at url: ws://localhost:65432/gui/ws?session_id=7beec213-5f64-457a-978b-c4d42c41e19c
[2023-11-07 17:03:23,734] [DEBUG] Session started
[2023-11-07 17:03:23,734] [DEBUG] Registered websocket for session 7beec213-5f64-457a-978b-c4d42c41e19c
[2023-11-07 17:03:24,003] [DEBUG] Loaded 757 documents into meilisearch in 0.8251471519470215 seconds for context provider file
[2023-11-07 17:03:24,005] [DEBUG] Loaded Meilisearch index
[2023-11-07 17:04:04,084] [DEBUG] Received GUI message {"messageType":"main_input","data":{"input":"/edit Refactor this to use a Module class instead of dumping all the info in module_data as a dictionary"}}
[2023-11-07 17:04:04,827] [ERROR] Error while running step: 
Traceback (most recent call last):

  File "server/continuedev/core/autopilot.py", line 437, in _run_singular_step

  File "/tmp/_MEILRTglD/continuedev/core/main.py", line 376, in __call__
    return await self.run(sdk)

  File "/tmp/_MEILRTglD/continuedev/core/steps.py", line 816, in run
    await self.stream_rif(rif, sdk)

  File "/tmp/_MEILRTglD/continuedev/core/steps.py", line 655, in stream_rif
    async for chunk in generator:

  File "/tmp/_MEILRTglD/continuedev/core/steps.py", line 635, in gen
    async for chunk in model_to_use.stream_chat(

  File "/tmp/_MEILRTglD/continuedev/libs/llm/base.py", line 406, in stream_chat
    async for chunk in self._stream_chat(messages=messages, options=options):

  File "/tmp/_MEILRTglD/continuedev/libs/llm/openai_free_trial.py", line 79, in _stream_chat
    async for item in resp:

  File "/tmp/_MEILRTglD/continuedev/libs/llm/proxy_server.py", line 67, in _stream_chat
    raise Exception(await resp.text())

Exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 114, in rate_limit_ip_middleware
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 213, in stream_chat
    args = parse_args(body)
           ^^^^^^^^^^^^^^^^
  File "/app/main.py", line 158, in parse_args
    raise ValueError(
ValueError: Invalid model: gpt-3.5-turbo-0613. Only 'gpt-3.5-turbo' and 'gpt-4' are supported.


You have reached your limit for free usage of our token. You can continue using Continue by entering your own OpenAI API key in VS Code settings.
```

My config file looks like this.

![image](https://github.com/continuedev/continue/assets/19474350/9ea2d61e-428d-4a6c-8c4a-d7db4583a5a4)

**Comment by sestinj** [comment] 2023-11-08 00:03
@iamjackg very likely it's because there's an error in the config file, but previously this would get reported in the UI and recently this functionality regressed. Working on putting it back in place right now.

And the Invalid model error is separate, this will be fixed as well

**Comment by iamjackg** [comment] 2023-11-08 00:08
That's odd. It happens even if I delete the config file, let the server recreate it, then use the UI to set up a model again. And even if I follow the instructions in the documentation to do it manually. The server logs don't mention any error in validating the config file either.

**Comment by sestinj** [comment] 2023-11-08 00:12
Interesting, it's possible I'm wrong then.

What are server and extension version so I can test directly?

**Comment by iamjackg** [comment] 2023-11-08 00:53
```
Running Continue server version 0.0.350
```

The extension is at 0.0.14

I suppose I could install the server manually as a package and debug through that. The bundled binary makes that difficult.

**Comment by iamjackg** [comment] 2023-11-08 03:23
Heh, if I try running the server manually from a virtualenv I run into #597. Nevermind I guess :laughing:

**Comment by iamjackg** [comment] 2023-11-08 18:19
Updated the extension to 0.0.16, which downloads a new version of the server, which doesn't start...

```
[2224772] Error loading Python lib '/tmp/_MEIfFYMGC/libpython3.11.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIfFYMGC/libpython3.11.so.1.0)
```

**Comment by sestinj** [comment] 2023-11-08 19:45
@iamjackg Are you on ubuntu 20.04 by chance? There was a breaking change in one of our dependencies that forced us to build on 22.04 until we have a better solution, which could cause what you're seeing with GLIBC

Previously I believe the issue was that the server version was out of date. 0.0.350 would have been a server version from an older VS Code extension version prior to the refactor, making it incompatible. As long as you can get a newer version of the server, it should work with IntelliJ 0.16. Unfortunately due to GLIBC best path might be `python -m contiuedev`

**Comment by sestinj** [comment] 2023-11-08 19:47
Can you share what exactly you tried that led to the #597 error? Want to be sure of the continuedev package version and anything else relevant about the environment so I can test this myself.

I do believe that 597 was prior to refactor

**Comment by iamjackg** [comment] 2023-11-09 15:41
I think #597 was caused by a version mismatch: I was using 0.0.14 with the latest version of continuedev straight from the repo.

I finally got it to work by installing the latest stable version from pypi, although I still run into strange behaviour from the extension: if I start the server manually and then start the IDE, the plugin will show the "Connecting to server" spinner forever. I have to click on the + to start a new session before I can actually interact with it.

**Comment by sestinj** [comment] 2023-11-09 21:35
@iamjackg I was absolutely seeing the same thing (spinning until you click "+") yesterday and was able to fix it for version 0.0.18

**Comment by iamjackg** [comment] 2023-12-08 19:56
Starting today, I've been getting this on startup. Clicking on Continue does take me to the usual input box.

![image](https://github.com/continuedev/continue/assets/19474350/f902d4ce-28da-49bb-9fbc-56385221c200)

**Comment by sestinj** [comment] 2023-12-16 00:38
@iamjackg Sorry about this bug. We have a huge update to JetBrains coming down the pipeline for early next week, which is why so few updates in the last couple weeks. Will share an update here when it's ready. Biggest thing is removing the need for the Python server

**Comment by sestinj** [comment] 2023-12-28 02:50
This issue is getting a bit unwieldy and related issues have been brought up for most of the sub-issues that I recall having been mentioned, so I am going to close this. Please do create separate issues if you'd like!

Also, the newest JetBrains version solves the r.map error above and many of the bugs mentioned previously

**Closed by sestinj** 2023-12-28 02:50 UTC
Labels: bug
