### ISSUE TITLE
Have you heard of VS 2022?

### ISSUE THREAD

**Issue by jalle007** [continuedev/continue#1083] opened 2024-04-05 11:32 UTC
### Validations

- [ ] I believe this is a way to improve. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

**Comment by Iamgood01** [comment] 2024-04-05 14:29
2022 version?

**Comment by JoepKockelkorn** [comment] 2024-05-27 19:37
Duplicate of #759

**Closed** 2024-11-01 08:05 UTC
