### ISSUE TITLE
StackOverflow query returns invalid JSON

### ISSUE THREAD

**Issue by alexsoyes** [continuedev/continue#994] opened 2024-03-19 14:45 UTC
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS M2
- Continue: Latest
- IDE: VSCode
```

### Description

When trying to use `/so` command.

### To reproduce

1. Go to the chat
2. Type "/so"
3. Hit enter
4. Wait :)

### Log output

```Continue error: Unexpected token '<', " <html><hea"... is not valid JSON```

```Shell
console.ts:137 [Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "8de66310-6e5c-400a-8d39-61e12af81c51",
    "messageType": "command/run",
    "data": {
      "input": "/so ",
      "history": [
        {
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "/so "
            }
          ]
        }
      ],
      "modelTitle": "Code LLAMA",
      "slashCommandName": "so",
      "contextItems": [],
      "historyIndex": 0,
      "selectedCode": []
    }
  }
}
```

**Comment by sestinj** [comment] 2024-07-03 22:00
closing as a duplicate of https://github.com/continuedev/continue/issues/1035

**Closed by sestinj** 2024-07-03 22:00 UTC
Labels: bug
