### ISSUE TITLE
When entering languages other than English in InlineEdit, characters appear garbled.

### ISSUE THREAD

**Issue by limty07** [continuedev/continue#1300] opened 2024-05-17 05:48 UTC
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: Windows 10 Pro 19045.4412
- Continue: v0.0.46
- IDE: Intellij IDEA 2024.1.1 #IU-241.15989.150
```

### Description

Edit highlighted code 
When entering languages other than English in InlineEdit, characters appear garbled.

### To reproduce

![image](https://github.com/continuedev/continue/assets/9198605/ff197888-9486-481a-a9d7-4c0641456a86)

**Comment by sestinj** [comment] 2024-05-20 22:20
Hi @limty07, it looks like this is a duplicate of the issue [here](https://github.com/continuedev/continue/issues/1249), so I'm going to close this one and keep you updated in that thread.

**Closed by sestinj** 2024-05-20 22:20 UTC
Labels: bug
