### ISSUE TITLE
Newest update overrides basic `ctrl+k` `ctrl+c` shortcut

### ISSUE THREAD

**Issue by jake-is-ESD-protected** [continuedev/continue#1193] opened 2024-04-26 11:19 UTC
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:Windows 10
- Continue:v0.8.25
- IDE: VSCodium 1.87
```

### Description

Newest update overrides basic `ctrl+k` `ctrl+c` shortcut. This shortcut is a default for block commenting on both VSCode and VSCodium. The shortcut is not listed under `continue`->`help center`. Opening the **default** (**not** user) `Default Keybindings.json`  reveals this line (among others)
```json
{ "key": "ctrl+k ctrl+c",         "command": "continue.openConfigJson" }
```
I am unable to edit this, neither in the UI or the `json` file directly. This file also can't be located to force an overwrite. Since I am very used to this shortcut and need it way more than `continue`'s shortcuts, I have no other option than to disable the extension until this is fixed. I assume that this shortcut is somewhat popular with other people as well, making me believe that this is a relevant issue.

### Recommended solutions
- Include the shortcut under `continue`->`help center`
- Change the default to some unused keybinding
- Add a proper `when` condition

### To reproduce

1. Install `continue` extension
2. Highlight some code to comment
3. Press `ctrl+k ctrl+c` to comment
4. `continue` `config.json` pops up

**Comment by sestinj** [comment] 2024-04-26 15:06
@jake-is-ESD-protected This is a duplicate of https://github.com/continuedev/continue/issues/1179, where I've acknowledged the feedback and made the change. This time I will wait until it's fully published to close the issue. Thanks for the feedback!

And in the meantime, I believe you can use the keyboard shortcut ctrl+k ctrl+s to open the keyboard shortcuts panel, search by keystroke, then right click and remove the keybinding:

<img width="1193" alt="Screenshot 2024-04-26 at 8 05 34 AM" src="https://github.com/continuedev/continue/assets/33237525/9ac87d41-0554-47c3-bf25-745f5f9b55a5">

**Comment by jake-is-ESD-protected** [comment] 2024-04-26 17:31
@sestinj Thanks for the clarification. Google search results truly are not that useful as they used to be. Interestingly, I can't do what you are showing on your screenshot. This, like any other change attempts, fails with
```
Error 'Error: Unable to write to the keybindings configuration file. 
Please open it to correct errors/warnings in the file and try again.' while editing the keybinding. 
Please open 'keybindings.json' file and check for errors.
```
Did you actually hit "Remove Keybinding" in your screenshot or did you stop at the right click? Could also be a permission issue, do you launch VSCode with administrative privileges? In any case, happy to see it fixed in the upcoming release.

**Comment by sestinj** [comment] 2024-04-27 06:58
That's interesting, yeah I did actually click remove. Probably that file exists in ~/.vscode somewhere, so depending on what permissions you would expect are required to write there...

But regardless 0.9.119 is now out so upgrading should resolve

**Closed** 2024-05-02 21:03 UTC
Labels: bug
