### ISSUE TITLE
Too many request 

### ISSUE THREAD

**Issue by ruthcyg** [continuedev/continue#1000] opened 2024-03-20 10:52 UTC
### Before submitting your bug report

- [X] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [X] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS:
- Continue:
- IDE:
```

### Description

Continue error: HTTP 429 Too Many Requests from https://proxy-server-blue-l6vsfbzhba-uw.a.run.app/stream_chat  {"message":"Too many requests. Please try again later."}

### To reproduce

![Screenshot 2024-03-20 162058](https://github.com/continuedev/continue/assets/76065759/26f4ef82-a591-410b-98ab-a842fc338876)

**Comment by Adityagaddhyan** [comment] 2024-03-20 14:35
Even I am facing the same.

**Comment by sestinj** [comment] 2024-03-20 16:14
@Adityagaddhyan @ruthcyg @AkshatSoni26 This should now be solved as long as you are on the latest version. It was mistaken rate limiting as we were attempting to prevent abuse.

Note that this will never happen if you use your own personal API key or a local model

**Comment by sestinj** [comment] 2024-03-20 16:16
Closing this as a duplicate of https://github.com/continuedev/continue/issues/993

**Closed by sestinj** 2024-03-20 16:16 UTC
Labels: bug

**Comment by libo2011cg** [comment] 2024-05-16 06:07
Encountered the same problem, and do not have their own local large model, how to deal with it？
