### ISSUE TITLE
Address already in use ('0.0.0.0', 65432)

### ISSUE THREAD

**Issue by renzor-fist** [continuedev/continue#372] opened 2023-08-12 01:28 UTC
**Describe the bug**

g'day... The continue server won't start on OSX Ventura 13.5 with:

```
python3 --version
Python 3.11.4
python --version
Python 3.11.4
python2 --version
Python 2.7.18
```

The `continue.log` file reads
```
Started server process [36787]
Waiting for application startup.
Application startup complete.
Uvicorn running on http://0.0.0.0:65432 (Press CTRL+C to quit)
Shutting down
Waiting for application shutdown.
Application shutdown complete.
Finished server process [36787]
Using selector: KqueueSelector
INFO:     Started server process [5629]
INFO:     Started server process [5627]
INFO:     Started server process [5632]
INFO:     Waiting for application startup.
INFO:     Waiting for application startup.
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Application startup complete.
INFO:     Application startup complete.
ERROR:    [Errno 48] error while attempting to bind on address ('0.0.0.0', 65432): address already in use
ERROR:    [Errno 48] error while attempting to bind on address ('0.0.0.0', 65432): address already in use
INFO:     Waiting for application shutdown.
INFO:     Uvicorn running on http://0.0.0.0:65432 (Press CTRL+C to quit)
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Application shutdown complete.
Testing logs
Cleaning up sessions
Testing logs
Cleaning up sessions
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Server.serve() done, defined at /Users/renzor/.continue/server/env/lib/python3.11/site-packages/uvicorn/server.py:61> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/Users/renzor/.continue/server/env/lib/python3.11/site-packages/uvicorn/server.py", line 159, in startup
    server = await loop.create_server(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1525, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 48] error while attempting to bind on address ('0.0.0.0', 65432): address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/renzor/.continue/server/env/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/renzor/.continue/server/env/lib/python3.11/site-packages/nest_asyncio.py", line 84, in run_until_complete
    self._run_once()
  File "/Users/renzor/.continue/server/env/lib/python3.11/site-packages/nest_asyncio.py", line 120, in _run_once
    handle._run()
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 350, in __wakeup
    self.__step()
  File "/Users/renzor/.continue/server/env/lib/python3.11/site-packages/nest_asyncio.py", line 196, in step
    step_orig(task, exc)
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/renzor/.continue/server/env/lib/python3.11/site-packages/uvicorn/server.py", line 76, in serve
    await self.startup(sockets=sockets)
  File "/Users/renzor/.continue/server/env/lib/python3.11/site-packages/uvicorn/server.py", line 169, in startup
    sys.exit(1)
SystemExit: 1
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Server.serve() done, defined at /Users/renzor/.continue/server/env/lib/python3.11/site-packages/uvicorn/server.py:61> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/Users/renzor/.continue/server/env/lib/python3.11/site-packages/uvicorn/server.py", line 159, in startup
    server = await loop.create_server(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1525, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 48] error while attempting to bind on address ('0.0.0.0', 65432): address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/renzor/.continue/server/env/lib/python3.11/site-packages/nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/renzor/.continue/server/env/lib/python3.11/site-packages/nest_asyncio.py", line 84, in run_until_complete
    self._run_once()
  File "/Users/renzor/.continue/server/env/lib/python3.11/site-packages/nest_asyncio.py", line 120, in _run_once
    handle._run()
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 350, in __wakeup
    self.__step()
  File "/Users/renzor/.continue/server/env/lib/python3.11/site-packages/nest_asyncio.py", line 196, in step
    step_orig(task, exc)
  File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/Users/renzor/.continue/server/env/lib/python3.11/site-packages/uvicorn/server.py", line 76, in serve
    await self.startup(sockets=sockets)
  File "/Users/renzor/.continue/server/env/lib/python3.11/site-packages/uvicorn/server.py", line 169, in startup
    sys.exit(1)
SystemExit: 1

```

But `lsof -i:65432` shows nothing running on that port.

**Comment by sestinj** [comment] 2023-08-12 01:34
@renzor-fist g'day. Looking into this now. I'm curious whether you have more than one VS Code window open - perhaps two instances are attempting to start the server at the same time. Also, I assume this is latest version, v0.0.300?

As a temporary solution, does reloading the window do any good?

**Comment by sestinj** [comment] 2023-08-12 05:59
Alright, thank you. This must be a zombie process stemming from the Node.js error encountered yesterday. Probably a force kill should do the trick, I'll update you soon

**Comment by sestinj** [comment] 2023-08-12 07:29
@renzor-fist Given that this was a new problem as of yesterday, I believe I understand the source of the problem and have solved it. Definitely want to keep this issue open until it's confidently verified that this was indeed fixed. Newest versions (v0.0.302+) include the relevant update.

**Comment by sestinj** [comment] 2023-08-13 18:24
Ok, looking back into it today. One possibility is that the process was somehow started by a different user, which would explain why it doesn't show when using lsof.

It would be useful to know whether a sudo lsof shows the process, or alternatively something like: sudo netstat -tanl | grep 65432

**Comment by sestinj** [comment] 2023-08-15 04:39
Hi @renzor-fist, I've successfully solved what I _believe_ was the cause of your problem. It is available in v0.0.307.

What I believe was the problem was that my GitHub Actions was not successfully updating the binary, leading to me falsely telling you that the problem was solved. I've also solved a few bugs along the way that additionally would have led to this outcome, and have made sure that "View Logs" will show what's going on.

**Comment by sestinj** [comment] 2023-08-15 20:54
That seems like the right intuition about what's wrong. You can check ~/.vscode/extensions/continue.continue-0.0.307/server/exe/run is the binary

**Comment by sestinj** [comment] 2023-08-21 22:17
@renzor-fist I've been looking into this today. There's a [switch in pyinstaller](https://pyinstaller.org/en/stable/man/pyi-makespec.html?highlight=--target-arch#mac-os-specific-options) to specify architecture, but [GitHub Actions doesn't yet support Apple Silicon](https://github.com/github/roadmap/issues/528). I can build a binary on my machine for arm64, but this isn't a reliable solution.

Depending on how much time you were willing to spend on this, it would be useful to know
a) (quick) whether Rosetta is installed (can check by open Applications in Finder, right clicking on Safari, "Show Info", and checking whether there is a checkbox like in the image below for "Open with Rosetta"). If it isn't already installed, then installing Rosetta could be a temporary solution.

<img width="257" alt="Screen Shot 2023-08-21 at 3 10 17 PM" src="https://github.com/continuedev/continue/assets/33237525/9272543a-080d-4fcc-bfba-22e9a1f814f3">

b) (less quick, don't worry about it unless you are legitimately curious)
- install pyinstaller with `pip3 install pyinstaller`
- `git clone https://github.com/continuedev/continue`
- `cd continue/continuedev`
- `poetry install` (if poetry isn't installed yet, then `curl -sSL https://install.python-poetry.org | python3 -`)
- cd `..`
- `pyinstaller run.spec`, which will create the binary at `./dist/run`, and you can then test to see whether a binary built on your own machine works

**Comment by sestinj** [comment] 2023-08-23 23:28
@renzor-fist ...finally...we are shipping with an M1-built binary, which I believe will solve this bug. The new version 0.0.323, and it should work out-of-the-box. If not, please let me know, don't want to keep you waiting any longer

**Comment by sestinj** [comment] 2023-08-28 22:20
@renzor-fist I'm going to close this issue since we've verified with other M1 users that it is solved—other problems should probably be classified in another issue, but if anything is still broken please create one or comment here : )

**Closed by sestinj** 2023-08-28 22:20 UTC
