### ISSUE TITLE
continue don't work

### ISSUE THREAD

**Issue by NetLSS** [continuedev/continue#1328] opened 2024-05-21 05:09 UTC
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: macOS Ventura 13.5.2
- Continue: 0.0.46
- IDE:Android Studio Koala | 2024.1.1 Canary 6
Build #AI-241.14494.240.2411.11731683, built on April 18, 2024
Runtime version: 17.0.10+0-17.0.10b1087.21-11609105 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
  ide.instant.shutdown=false
  ide.balloon.shadow.size=0
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  ide.images.show.chessboard=true
Non-Bundled Plugins:
  com.lilittlecat.intellij-chatgpt (1.1.1)
  PlantUML integration (7.10.1-IJ2023.2)
  com.intellij.marketplace (241.14494.288)
  com.github.continuedev.continueintellijextension (0.0.46)
  ChatGPT (3.2.1-241)
  com.caldonazzi.alessandro.uml (0.2.0)
  idea.plugin.protoeditor (241.14494.150)
  izhangzhihao.rainbow.brackets (2024.2.3-241)
  plantuml-parser (0.0.9)
  dev.arunkumar.scabbard.idea-plugin (0.5.0)
  com.suusan2go.kotlin-fill-class (1.0.23)
  com.github.copilot (1.5.2.5345)
  com.rookout.intellij-plugin (2.8.6)
```

**Comment by sestinj** [comment] 2024-06-14 16:07
@NetLSS @GAM3RG33K it looks like this is a duplicate of https://github.com/continuedev/continue/issues/596

**Closed by sestinj** 2024-06-14 16:07 UTC
Labels: bug
